-- NM Database for FFXI
-- Contains notorious monsters organized by expansion/region

local nm_database = {}

-- Create a set for fast lookup
nm_database.nm_set = {}
nm_database.nm_details = {}

-- Helper function to add NMs
local function add_nm(name, zone, level, family)
    nm_database.nm_set[name:lower()] = true
    nm_database.nm_details[name:lower()] = {
        name = name,
        zone = zone,
        level = level,
        family = family
    }
end

-- Low Level (1-20)
add_nm("Fungus Beetle", "West Sarutabaruta", 5, "Beetle")
add_nm("Tococo", "South Gustaberg", 5, "Bird")
add_nm("Amanita", "West Ronfaure", 5, "Funguar")
add_nm("Jaggedy-Eared Jack", "West Ronfaure", 8, "Rabbit")
add_nm("Bigmouth Billy", "East Ronfaure", 9, "Worm")
add_nm("Bubbly Bernie", "South Gustaberg", 9, "Crab")
add_nm("Tom Tit Tat", "West Sarutabaruta", 9, "Mandragora")
add_nm("Leaping Lizzy", "South Gustaberg", 10, "Lizard")
add_nm("Bogy", "West Ronfaure", 10, "Skeleton")
add_nm("Sharp-Eared Ropipi", "East Sarutabaruta", 10, "Rabbits")
add_nm("Maighdean Uaine", "North Gustaberg", 11, "Sapling")
add_nm("Bedrock Barry", "North Gustaberg", 11, "Worm")
add_nm("Thousandarm Deshglesh", "Ghelsba Outpost", 11, "Orc")
add_nm("Hundredscar Hajwaj", "Fort Ghelsba", 11, "Orc")
add_nm("Carnero", "North Gustaberg", 12, "Ram")
add_nm("Bu'Ghi Howlblade", "Palborough Mines", 12, "Quadav")
add_nm("Nunyenunc", "West Sarutabaruta", 12, "Bird")
add_nm("Numbing Norman", "West Sarutabaruta", 12, "Bee")
add_nm("Swamfisk", "East Ronfaure", 12, "Pugil")
add_nm("Rambukk", "East Ronfaure", 12, "Ram")
add_nm("Bu'Ghi Howlblade", "Palborough Mines", 12, "Quadav")
add_nm("Juu Duzu the Whirlwind", "Giddeus", 13, "Yagudo")
add_nm("Bloody Vrukwuk", "Ghelsba Outpost", 14, "Orc")
add_nm("Fogweaver Mozzfuzz", "Ghelsba Outpost", 14, "Orc")
add_nm("Haty", "Konschtat Highlands", 14, "Hound")
add_nm("Bendigeit Vran", "Konschtat Highlands", 14, "Shadow")
add_nm("Yara Ma Yha Who", "Tahrongi Canyon", 14, "Sapling")
add_nm("Gale Bats", "North Gustaberg", 15, "Bat")
add_nm("Gavotvut", "Inner Horutoto Ruins", 15, "Cardian")
add_nm("Cargo Crab Colin", "Outer Horutoto Ruins", 15, "Crab")
add_nm("Steam Cleaner", "Zeruhn Mines", 15, "Bomb")
add_nm("Ghillie Dhu", "Konschtat Highlands", 15, "Sapling")
add_nm("Zi'Ghi Boneeater", "Palborough Mines", 15, "Quadav")
add_nm("Zi'Ghi Boneeater", "Palborough Mines", 15, "Quadav")
add_nm("Eyy Mon the Ironbreaker", "Giddeus", 16, "Yagudo")
add_nm("Zhuu Buxu the Silent", "Giddeus", 16, "Yagudo")
add_nm("Hoo Mjuu the Torrent", "Giddeus", 16, "Yagudo")
add_nm("Habrok", "Tahrongi Canyon", 16, "Bird")
add_nm("Bomb King", "Outer Horutoto Ruins", 16, "Bomb")
add_nm("Slumbering Samwell", "La Theine Plateau", 17, "Sheep")
add_nm("Qu'Vho Deathhurler", "Palborough Mines", 17, "Quadav")
add_nm("Ashmaker Gotblut", "Yughott Grotto", 17, "Orc")
add_nm("Qu'Vho Deathhurler", "Palborough Mines", 17, "Quadav")
add_nm("Spiny Spipi", "Tahrongi Canyon", 18, "Cactuar")
add_nm("Tumbling Truffle", "La Theine Plateau", 19, "Funguar")
add_nm("Serpopard Ishtar", "Tahrongi Canyon", 19, "Dhalmel")

-- Mid Level (20-40)
add_nm("Backoo", "Buburimu Peninsula", 20, "Fly")
add_nm("Buburimboo", "Buburimu Peninsula", 20, "Ghost")
add_nm("Valkurm Emperor", "Valkurm Dunes", 20, "Fly")
add_nm("Teporingo", "Dangruf Wadi", 20, "Rabbit")
add_nm("Orcish Panzer", "Fort Ghelsba", 20, "Warmachine")
add_nm("Vuu Puqu the Beguiler", "Giddeus", 21, "Yagudo")
add_nm("Wake Warder Wanda", "Buburimu Peninsula", 22, "Crab")
add_nm("No'Mho Crimsonarmor", "Palborough Mines", 22, "Quadav")
add_nm("Maltha", "Inner Horutoto Ruins", 22, "Slime")
add_nm("No'Mho Crimsonarmor", "Palborough Mines", 22, "Quadav")
add_nm("Golden Bat", "Gusgen Mines", 23, "Bat")
add_nm("Doppelganger Dio", "Outer Horutoto Ruins", 23, "Shadow")
add_nm("Doppelganger Gog", "Outer Horutoto Ruins", 23, "Shadow")
add_nm("Chocoboleech", "Dangruf Wadi", 24, "Leech")
add_nm("Stray Mary", "Gusgen Mines", 25, "Ghost")
add_nm("Wirbelwind", "Maze of Shakhrami", 25, "Fly")
add_nm("Bi'Gho Headtaker", "Beadeaux", 25, "Quadav")
add_nm("Nocuous Weapon", "Inner Horutoto Ruins", 25, "Evil Weapon")
add_nm("Quu Xijo the Illusory", "Giddeus", 25, "Yagudo")
add_nm("Bi'Gho Headtaker", "Beadeaux", 25, "Quadav")
add_nm("Quu Domi the Gallant", "Maze of Shakhrami", 26, "Quadav")
add_nm("Black Triple Stars", "Rolanberry Fields", 26, "Bats")
add_nm("Lumbering Lambert", "La Theine Plateau", 27, "Ram")
add_nm("Rampaging Ram", "Konschtat Highlands", 27, "Ram")
add_nm("Highlander Lizard", "Konschtat Highlands", 27, "Lizard")
add_nm("Tottering Toby", "Batallia Downs", 27, "Sapling")
add_nm("Daggerclaw Dracos", "Meriphataud Mountains", 27, "Raptor")
add_nm("Padfoot", "Gusgen Mines", 28, "Hound")
add_nm("Herbage Hunter", "Tahrongi Canyon", 28, "Crawler")
add_nm("Geyser Lizard", "Dangruf Wadi", 28, "Lizard")
add_nm("Epialtes", "Lower Delkfutt's Tower", 28, "Gigas")
add_nm("Hippolytos", "Lower Delkfutt's Tower", 28, "Gigas")
add_nm("Helldiver", "Buburimu Peninsula", 29, "Bird")
add_nm("Mee Deggi the Punisher", "Jugner Forest", 30, "Orc")
add_nm("Argus", "Meriphataud Mountains", 30, "Fly")
add_nm("Gargoyle", "Gusgen Mines", 30, "Gargoyle")
add_nm("Goblin Archaeologist", "La Theine PlateauKonschtat HighlandsTahrongi Canyon", 30, "Goblin")
add_nm("Morion Worm", "Korroloka Tunnel", 30, "Worm")
add_nm("Moo Ouzi the Swiftblade", "Castle Oztroja", 30, "Yagudo")
add_nm("Ge'Dha Evileye", "Beadeaux", 30, "Quadav")
add_nm("Da'Dha Hundredmask", "Beadeaux", 30, "Quadav")
add_nm("Eurymedon", "Lower Delkfutt's Tower", 30, "Gigas")
add_nm("Ge'Dha Evileye", "Beadeaux", 30, "Quadav")
add_nm("Da'Dha Hundredmask", "Beadeaux", 30, "Quadav")
add_nm("Tigerbane Bakdak", "Davoi", 31, "Orc")
add_nm("Panzer Percival", "Jugner Forest", 32, "Beetle")
add_nm("Falcatus Aranei", "Korroloka Tunnel", 32, "Spider")
add_nm("Eurytos", "Middle Delkfutt's Tower", 32, "Gigas")
add_nm("Naa Yaku the Everliving", "Meriphataud Mountains", 33, "Yagudo")
add_nm("Sandworm", "Pashhow Marshlands", 33, "Worm")
add_nm("Steelbiter Gudrud", "Davoi", 33, "Orc")
add_nm("Hercules Beetle", "Carpenters' Landing", 34, "Beetle")
add_nm("Jolly Green", "Rolanberry Fields", 35, "Goblin")
add_nm("Stinging Sophie", "Sauromugue Champaign", 35, "Bee")
add_nm("Trickster Kinetix", "Qufim Island", 35, "Evil Weapon")
add_nm("Mycophile", "Carpenters' Landing", 35, "Funguar")
add_nm("Meteormauler Zhagtegg", "Jugner Forest", 35, "Orc")
add_nm("Burned Bergmann", "Gusgen Mines", 36, "Ghost")
add_nm("Asphyxiated Amsel", "Gusgen Mines", 36, "Ghost")
add_nm("Crushed Krause", "Gusgen Mines", 36, "Ghost")
add_nm("Pulverized Pfeffer", "Gusgen Mines", 36, "Ghost")
add_nm("Smothered Schmidt", "Gusgen Mines", 36, "Ghost")
add_nm("Wounded Wurfel", "Gusgen Mines", 36, "Ghost")
add_nm("Mimas", "Upper Delkfutt's Tower", 36, "Gigas")
add_nm("Porphyrion", "Upper Delkfutt's Tower", 36, "Gigas")
add_nm("Zo'Khu Blackcloud", "Beadeaux", 36, "Quadav")
add_nm("Zo'Khu Blackcloud", "Beadeaux", 36, "Quadav")
add_nm("Bo'Who Warmonger", "Pashhow Marshlands", 37, "Quadav")
add_nm("Dame Blanche", "Korroloka Tunnel", 37, "Ghost")
add_nm("Orctrap", "Carpenters' Landing", 37, "Flytrap")
add_nm("Stubborn Dredvodd", "Phanauet Channel", 37, "Orc")
add_nm("Coo Keja the Unseen", "Meriphataud Mountains", 37, "Yagudo")
add_nm("Bo'Who Warmonger", "Pashhow Marshlands", 37, "Quadav")
add_nm("Eldritch Edge", "Rolanberry Fields", 38, "Weapon")
add_nm("Myxomycete", "Sauromugue Champaign", 38, "Funguar")
add_nm("Aroma Leech", "Ordelle's Caves", 38, "Leech")
add_nm("Poisonhand Gnadgad", "Davoi", 39, "Orc")
add_nm("Drooling Daisy", "Rolanberry Fields", 39, "Morbol")
add_nm("Masan", "Sea Serpent Grotto", 39, "Leech")

-- High Level (40-60)
add_nm("Helm Beetle", "Crawlers' Nest", 40, "Beetle")
add_nm("Chonchon", "Pashhow Marshlands", 40, "Fly")
add_nm("Leech King", "Ordelle's Caves", 40, "Leech")
add_nm("Zuug the Shoreleaper", "Sauromugue Champaign", 40, "Sahagin")
add_nm("Celphie", "Konschtat Highlands", 40, "Sheep")
add_nm("Namtar", "Sea Serpent Grotto", 40, "Skeleton")
add_nm("Aroma Fly", "Gusgen Mines", 40, "Fly")
add_nm("Aroma Crawler", "Maze of Shakhrami", 40, "Crawler")
add_nm("Go'Bhu Gascon", "Beadeaux", 41, "Quadav")
add_nm("Kirata", "Beaucedine Glacier", 41, "Tiger")
add_nm("Go'Bhu Gascon", "Beadeaux", 41, "Quadav")
add_nm("Tremor Ram", "Konschtat Highlands", 42, "Ram")
add_nm("Morbolger", "Ordelle's Caves", 42, "Morbol")
add_nm("Foul Meat", "Gusgen Mines", 43, "Doomed")
add_nm("King Arthro", "Crawlers' Nest", 45, "Crawler")
add_nm("Bloodtear Baldurf", "Davoi", 45, "Orc")
add_nm("Hawkeyed Dnatbat", "Beadeaux", 45, "Quadav")
add_nm("Yaa Haqa the Profane", "Castle Oztroja", 45, "Yagudo")
add_nm("Fraelissa", "Konschtat Highlands", 45, "Skeleton")
add_nm("Steelfleece Baldarich", "La Theine Plateau", 45, "Ram")
add_nm("Golden-tongued Culberry", "Gustav Tunnel", 45, "Tonberry")
add_nm("Weeping Willow", "Batallia Downs", 45, "Treant")
add_nm("Blubbery Bulge", "Davoi", 45, "Slime")
add_nm("Guardian Crawler", "Crawlers' Nest", 45, "Crawler")
add_nm("De'Vyu Headhunter", "Beadeaux", 45, "Quadav")
add_nm("Vodyanoi", "Phanauet Channel", 45, "Doomed")
add_nm("De'Vyu Headhunter", "Beadeaux", 45, "Quadav")
add_nm("Juggler Hecatomb", "Gusgen Mines", 46, "Evil Weapon")
add_nm("Intulo", "Bibiki Bay", 46, "Eft")
add_nm("Eyegouger", "Batallia Downs", 46, "Birds")
add_nm("Bloodpool Vorax", "La Theine Plateau", 47, "Tiger")
add_nm("Ga'Bhu Unvanquished", "Beadeaux", 47, "Quadav")
add_nm("Meww the Turtlerider", "Yuhtunga Jungle", 47, "Sahagin")
add_nm("Ga'Bhu Unvanquished", "Beadeaux", 47, "Quadav")
add_nm("Cactrot Rapido", "Western Altepa Desert", 48, "Cactuar")
add_nm("Shadow Eye", "Xarcabard", 48, "Ahriman")
add_nm("Wuur the Sandcomber", "Sea Serpent Grotto", 48, "Sahagin")
add_nm("Seww the Squidlimbed", "Sea Serpent Grotto", 48, "Sahagin")
add_nm("Fyuu the Seabellow", "Sea Serpent Grotto", 48, "Sahagin")
add_nm("Serra", "Bibiki Bay - Purgonorgo Isle", 49, "Pugil")
add_nm("Qull the Shellbuster", "Sea Serpent Grotto", 49, "Sahagin")
add_nm("Dune Widow", "Western Altepa Desert", 50, "Spider")
add_nm("Dum-a-lum", "La Theine Plateau", 50, "Goblin")
add_nm("Sabotender Bailarin", "Eastern Altepa Desert", 50, "Cactuar")
add_nm("Ungur", "Gustav Tunnel", 50, "Troll")
add_nm("Drone Crawler", "Crawlers' Nest", 50, "Crawler")
add_nm("Rose Garden", "Yuhtunga Jungle", 50, "Morbol")
add_nm("Mysticmaker Profblix", "Labyrinth of Onzozo", 50, "Goblin")
add_nm("Bugbear Strongman", "Oldton Movalpolos", 50, "Bugbear")
add_nm("Gloomanita", "North Gustaberg (S)", 50, "Funguar")
add_nm("Goblin Wolfman", "Oldton Movalpolos", 50, "Moblin")
add_nm("Torama", "Yhoator Jungle", 52, "Tiger")
add_nm("Old Two-Wings", "Garlaige Citadel", 52, "Giant Bat")
add_nm("Bune", "Gustav Tunnel", 53, "Skeleton")
add_nm("Balam-Quitz", "Sauromugue Champaign (S)", 53, "Coeurl")
add_nm("Skewer Sam", "Garlaige Citadel", 54, "Cockatrice")
add_nm("Kreutzet", "Batallia Downs", 55, "Skeleton")
add_nm("Bistre-hearted Malberry", "Yhoator Jungle", 55, "Mandragora")
add_nm("Cactuar Cantautor", "Eastern Altepa Desert", 55, "Cactuar")
add_nm("Phantom", "Eldieme Necropolis", 55, "Ghost")
add_nm("Lumber Jack", "Batallia Downs", 55, "Beetle")
add_nm("Waraxe Beak", "Meriphataud Mountains", 55, "Cockatrice")
add_nm("Roc", "Sauromugue Champaign", 55, "Roc")
add_nm("Goblinsavior Heronox", "Gustav Tunnel", 55, "Goblin")
add_nm("Bright-handed Kunberry", "Yhoator Jungle", 55, "Tonberry")
add_nm("Edacious Opo-opo", "Yhoator Jungle", 55, "Opo-opo")
add_nm("Ziphius", "Misareaux Coast", 55, "Pugil")
add_nm("Mischievous Micholas", "Sanctuary of Zi'Tah", 56, "Mandragora")
add_nm("Centurio X-I", "Quicksand Caves", 56, "Antica")
add_nm("Boll Weevil", "Jugner Forest (S)", 56, "Beetle")
add_nm("Centurio XII-I", "Eastern Altepa Desert", 56, "Antica")
add_nm("Colorful Leshy", "Lufaise Meadows", 56, "Treant")
add_nm("Unstable Cluster", "Riverne - Site B01", 56, "Cluster")
add_nm("Dynast Beetle", "Crawlers' Nest", 56, "Beetle")
add_nm("Duke Decapod", "Bibiki Bay", 57, "Crab")
add_nm("Ahtu", "Batallia Downs", 57, "Mandragora")
add_nm("Sagittarius X-XIII", "Quicksand Caves", 57, "Antica")
add_nm("Lamina", "Rolanberry Fields (S)", 57, "Mandragora")
add_nm("Pahh the Gullcaller", "Sea Serpent Grotto", 57, "Sahagin")
add_nm("Habetrot", "Temple of Uggalepih", 57, "Crawler")
add_nm("Hoar-knuckled Chromosome", "Yhoator Jungle", 58, "Goblin")
add_nm("Ogygos", "Toraimarai Canal", 58, "Leech")
add_nm("Lich C Magnus", "Eldieme Necropolis", 58, "Skeleton")
add_nm("Bisque-heeled Sunberry", "Yhoator Jungle", 58, "Tonberry")
add_nm("Fradubio", "Jugner Forest", 58, "Treant")
add_nm("Hyakinthos", "Sauromugue Champaign (S)", 58, "Mandragora")
add_nm("Flauros", "Temple of Uggalepih", 59, "Coeurl")
add_nm("Balor", "Sacrarium", 59, "Fomor")
add_nm("Luaith", "Sacrarium", 59, "Fomor")
add_nm("Lobais", "Sacrarium", 59, "Fomor")
add_nm("Caithleann", "Sacrarium", 59, "Fomor")
add_nm("Indich", "Sacrarium", 59, "Fomor")

-- Endgame (60-75)
add_nm("Sturmtiger", "Batallia Downs", 60, "Tiger")
add_nm("Supplice", "Beaucedine Glacier", 60, "Demon")
add_nm("Isonade", "Sanctuary of Zi'Tah", 60, "Sea Monk")
add_nm("Deadly Dodo", "Lufaise Meadows", 60, "Dodo")
add_nm("Taxim", "King Ranperre's Tomb", 60, "Skeleton")
add_nm("Demonic Rose", "Toraimarai Canal", 60, "Rose")
add_nm("Skull of Envy", "Eldieme Necropolis", 60, "Skeleton")
add_nm("Skull of Gluttony", "Eldieme Necropolis", 60, "Skeleton")
add_nm("Skull of Greed", "Eldieme Necropolis", 60, "Skeleton")
add_nm("Skull of Lust", "Eldieme Necropolis", 60, "Skeleton")
add_nm("Skull of Pride", "Eldieme Necropolis", 60, "Skeleton")
add_nm("Skull of Sloth", "Eldieme Necropolis", 60, "Skeleton")
add_nm("Skull of Wrath", "Eldieme Necropolis", 60, "Skeleton")
add_nm("La Velue", "Batallia Downs (S)", 60, "Tiger")
add_nm("Nussknacker", "Quicksand Caves", 60, "Lizard")
add_nm("Woodland Sage", "Yhoator Jungle", 60, "Treant")
add_nm("Sea Horror", "Ship bound for Mhaura", 60, "Sea Monk")
add_nm("Taisaijin", "Ranguemont Pass", 60, "Hecteyes")
add_nm("Demonic Tiphia", "Crawlers' Nest", 60, "Bee")
add_nm("Peg Powler", "Labyrinth of Onzozo", 61, "Sea Monk")
add_nm("Worr the Clawfisted", "Sea Serpent Grotto", 61, "Sahagin")
add_nm("Colerain", "Beaucedine Glacier", 62, "Buffalo")
add_nm("Gwyllgi", "King Ranperre's Tomb", 62, "Hound")
add_nm("Oni Carcass", "Toraimarai Canal", 62, "Skeleton")
add_nm("Goliath", "Fei'Yin", 62, "Golem")
add_nm("Sea Hog", "Sea Serpent Grotto", 62, "Pugil")
add_nm("Death from Above", "Temple of Uggalepih", 62, "Bee")
add_nm("Zoredonite", "Manaclipper", 62, "Uragnite")
add_nm("Keeper of Halidom", "Sanctuary of Zi'Tah", 63, "Golem")
add_nm("Kurrea", "Lufaise Meadows", 63, "Sheep")
add_nm("Northern Shadow", "Fei'Yin", 63, "Shadow")
add_nm("Eastern Shadow", "Fei'Yin", 63, "Shadow")
add_nm("Western Shadow", "Fei'Yin", 63, "Shadow")
add_nm("Southern Shadow", "Fei'Yin", 63, "Shadow")
add_nm("Gugru Orobon(Fishing)", "Open sea route to Al Zahbi", 63, "Orobon")
add_nm("Sewer Syrup", "Bostaunieux Oubliette", 64, "Slime")
add_nm("Queen Crawler", "Crawlers' Nest", 64, "Crawler")
add_nm("Matron Crawler", "Crawlers' Nest", 64, "Crawler")
add_nm("Voll the Sharkfinned", "Sea Serpent Grotto", 64, "Sahagin")
add_nm("Mouu the Waverider", "Sea Serpent Grotto", 64, "Sahagin")
add_nm("Gargantua", "Beaucedine Glacier", 65, "Giant")
add_nm("Nue", "Labyrinth of Onzozo", 65, "Bat")
add_nm("Noble Mold", "Boyahda Tree", 65, "Funguar")
add_nm("Awd Goggie", "Misareaux Coast", 65, "Hound")
add_nm("Cemetery Cherry", "King Ranperre's Tomb", 65, "Ghost")
add_nm("Amikiri", "Den of Rancor", 65, "Crab")
add_nm("Antican Praefectus", "Quicksand Caves", 65, "Antica")
add_nm("Antican Proconsul", "Quicksand Caves", 65, "Antica")
add_nm("Cancer", "Kuftal Tunnel", 65, "Crab")
add_nm("Sozu Bliberry", "Den of Rancor", 65, "Tonberry")
add_nm("Sozu Terberry", "Temple of Uggalepih", 65, "Tonberry")
add_nm("Tonberry Kinq", "Temple of Uggalepih", 65, "Tonberry")
add_nm("Hastatus XI-XII", "Quicksand Caves", 65, "Antica")
add_nm("Dyinyinga", "Rolanberry Fields (S)", 65, "Slugs")
add_nm("Megalobugard", "Lufaise Meadows", 66, "Bugard")
add_nm("Hellion", "Labyrinth of Onzozo", 66, "Doomed")
add_nm("Amemet", "Kuftal Tunnel", 66, "Lizard")
add_nm("Ellyllon", "Boyahda Tree", 66, "Funguar")
add_nm("Novv the Whitehearted", "Sea Serpent Grotto", 66, "Sahagin")
add_nm("Carmine-tailed Janberry", "Den of Rancor", 66, "Tonberry")
add_nm("Antican Magister", "Quicksand Caves", 66, "Antica")
add_nm("Sacrificial Goblet", "Temple of Uggalepih", 66, "Magic Pot")
add_nm("Splacknuck", "Bibiki Bay", 66, "Eft")
add_nm("Blackbeard", "Ship bound for Mhaura", 67, "Skeleton")
add_nm("Celeste-eyed Tozberry", "Den of Rancor", 67, "Tonberry")
add_nm("Citipati", "Attohwa Chasm", 67, "Corse")
add_nm("Soulstealer Skullnix", "Labyrinth of Onzozo", 68, "Skeleton")
add_nm("Darter", "Ro'Maeve", 68, "Roc")
add_nm("Centurio IV-VII", "Kuftal Tunnel", 68, "Antica")
add_nm("Beryl-footed Molberry", "Misareaux Coast", 68, "Mandragora")
add_nm("Enagakure", "Den of Rancor", 68, "Tonberry")
add_nm("Uleguerand Tiger", "Uleguerand Range", 68, "Tiger")
add_nm("Baronet Romwe", "Castle Zvahl Keep", 68, "Demon")
add_nm("Baron Vapula", "Castle Zvahl Keep", 68, "Demon")
add_nm("Viscount Morax", "Castle Zvahl Keep", 68, "Demon")
add_nm("Sabotender Mariachi", "Kuftal Tunnel", 68, "Sabotender")
add_nm("Cwn Cyrff", "Eldieme Necropolis", 68, "Hound")
add_nm("Bloodthirster Madkix", "Kuftal Tunnel", 69, "Goblin")
add_nm("Arachne", "Kuftal Tunnel", 69, "Spider")
add_nm("Yowie", "Kuftal Tunnel", 69, "Raptor")
add_nm("Aquarius", "Boyahda Tree", 70, "Elemental")
add_nm("Shikigami Weapon", "Shrine of Ru'Avitau", 70, "Weapon")
add_nm("Eba", "Ifrit's Cauldron", 70, "Bomb")
add_nm("Gotoh Zha the Redolent", "Wajaom Woodlands", 70, "Orc")
add_nm("Sozu Sarberry", "Den of Rancor", 70, "Tonberry")
add_nm("Maat", "Balga's Dais", 70, "Hume")
add_nm("Tenzen", "Waughroon Shrine", 70, "Samurai")
add_nm("Shii", "Bostaunieux Oubliette", 70, "Hound")
add_nm("Capricious Cassie", "Fei'Yin", 70, "Morbol")
add_nm("Diamond Daig", "Quicksand Caves", 70, "Beetle")
add_nm("Phantom Worm", "Kuftal Tunnel", 70, "Worm")
add_nm("Wyvernpoacher Drachlox", "Gustav Tunnel", 70, "Goblin")
add_nm("Friar Rush", "Den of Rancor", 70, "Bomb")
add_nm("Biast", "Xarcabard", 70, "Dragon")
add_nm("Silverhook", "Ship bound for Mhaura", 70, "Skeleton")
add_nm("White Coney", "Uleguerand Range", 70, "Rabbit")
add_nm("Black Coney", "Uleguerand Range", 70, "Rabbit")
add_nm("Bloodsucker", "Bostaunieux Oubliette", 71, "Leech")
add_nm("Dirtyhanded Gochakzuk", "Davoi", 71, "Orc")
add_nm("Ixtab", "Upper Delkfutt's Tower", 71, "Ghost")
add_nm("Foreseer Oramix", "Ifrit's Cauldron", 71, "Goblin")
add_nm("Snow Maiden", "Uleguerand Range", 71, "Snoll")
add_nm("Tawny-fingered Mugberry", "Den of Rancor", 71, "Tonberry")
add_nm("Unut", "Boyahda Tree", 72, "Mandragora")
add_nm("Tribunus VII-I", "Quicksand Caves", 72, "Antica")
add_nm("Ash Dragon", "Ifrit's Cauldron", 72, "Dragon")
add_nm("Zoraal Ja's Pkuucha", "Wajaom Woodlands", 72, "Wivre")
add_nm("Sozu Rogberry", "Temple of Uggalepih", 72, "Tonberry")
add_nm("Bonnacon", "Uleguerand Range", 72, "Buffalo")
add_nm("Tonberry Pursuer", "Den of Rancor", 72, "Tonberry")
add_nm("Phanduron the Condemned", "Bostaunieux Oubliette", 72, "Shadow")
add_nm("Drexerion the Condemned", "Bostaunieux Oubliette", 72, "Shadow")
add_nm("Orcish Warlord", "Monastic Cavern", 72, "Orc")
add_nm("Orcish Hexspinner", "Monastic Cavern", 72, "Orc")
add_nm("Pallas", "Upper Delkfutt's Tower", 72, "Gigas")
add_nm("Antican Legatus", "Quicksand Caves", 72, "Antica")
add_nm("Proconsul XII", "Quicksand Caves", 72, "Antica")
add_nm("Antican Tribunus", "Quicksand Caves", 72, "Antica")
add_nm("Triarius X-XV", "Quicksand Caves", 72, "Antica")
add_nm("Tonberry Decapitator", "Den of Rancor", 72, "Tonberry")
add_nm("Tonberry Tracker", "Den of Rancor", 72, "Tonberry")
add_nm("Tarasque", "Ifrit's Cauldron", 72, "Lizard")
add_nm("Jaded Jody", "Bhaflau Thickets", 73, "Mandragora")
add_nm("Oupire", "Velugannon Palace", 73, "Bat")
add_nm("Tyrannic Tunnok", "Ifrit's Cauldron", 73, "Scorpion")
add_nm("Mountain Worm", "Uleguerand Range", 73, "Worm")
add_nm("Orobon(Fishing)", "Open sea route to Al Zahbi", 73, "Orobon")
add_nm("Peallaidh", "Caedarva Mire", 73, "Sheep")
add_nm("Zoraal Ja's Pkuucha", "Wajaom Woodlands", 73, "Colibri")
add_nm("Lil' Apkallu", "Arrapago Reef", 74, "Apkallu")
add_nm("Tonberry Stalker", "Temple of Uggalepih", 74, "Tonberry")
add_nm("Lord of Onzozo", "Labyrinth of Onzozo", 74, "Sea Monk")
add_nm("Ose", "Labyrinth of Onzozo", 74, "Coeurl")
add_nm("Lindwurm", "Ifrit's Cauldron", 74, "Raptor")
add_nm("Father Frost", "Uleguerand Range", 74, "Snoll")

-- Level 75 Era (75-90)
add_nm("Aspidochelone", "Phomiuna Aqueducts", 75, "Adamantoise")
add_nm("Adamantoise", "Valley of Sorrows", 75, "Adamantoise")
add_nm("Simurgh", "Ro'Maeve", 75, "Roc")
add_nm("Serket", "Quicksand Caves", 75, "Scorpion")
add_nm("Guivre", "Ifrit's Cauldron", 75, "Wyrm")
add_nm("Odqan", "Wajaom Woodlands", 75, "Tiger")
add_nm("Sarameya", "Mount Zhayolm", 75, "Cerberus")
add_nm("Mimic", "Various", 75, "Mimic")
add_nm("Cursed Chest", "Various", 75, "Mimic")
add_nm("Behemoth", "Behemoth's Dominion", 75, "Behemoth")
add_nm("Archlich Taber'quoan", "Eldieme Necropolis", 75, "Skeleton")
add_nm("Duke Gomory", "Castle Zvahl Keep", 75, "Demon")
add_nm("Nargun", "Velugannon Palace", 75, "Demon")
add_nm("Hpemde", "Ru'Aun Gardens", 75, "Hpemde")
add_nm("Orcish Overlord", "Monastic Cavern", 75, "Orc")
add_nm("Diamond Quadav", "Qulun Dome", 75, "Quadav")
add_nm("Narasimha", "Labyrinth of Onzozo", 75, "Manticore")
add_nm("Yagudo Avatar", "Castle Oztroja", 75, "Yagudo")
add_nm("Alkyoneus", "Upper Delkfutt's Tower", 75, "Gigas")
add_nm("Antican Consul", "Quicksand Caves", 75, "Antica")
add_nm("Ocean Sahagin", "Sea Serpent Grotto", 75, "Sahagin")
add_nm("Ambusher Antlion", "Attohwa Chasm", 75, "Antlion")
add_nm("Lamia No.3", "Arrapago Reef", 76, "Lamia")
add_nm("Count Bifrons", "Castle Zvahl Keep", 76, "Demon")
add_nm("Crimson-toothed Pawberry", "Temple of Uggalepih", 76, "Tonberry")
add_nm("Grand Duke Batym", "Castle Zvahl Baileys", 76, "Demon")
add_nm("Duke Haborym", "Castle Zvahl Baileys", 76, "Demon")
add_nm("Marquis Allocen", "Castle Zvahl Baileys", 76, "Demon")
add_nm("Marquis Amon", "Castle Zvahl Baileys", 76, "Demon")
add_nm("Nightmare Vase", "Ro'Maeve", 76, "Magic Pot")
add_nm("Cerberus", "Mount Zhayolm", 77, "Cerberus")
add_nm("Duke Berith", "Castle Zvahl Keep", 77, "Demon")
add_nm("Emergent Elm", "Bhaflau Thickets", 77, "Treant")
add_nm("Baobhan Sith", "Gustav Tunnel", 77, "Ghost")
add_nm("Suzaku", "Ru'Aun Gardens", 78, "Wyrm")
add_nm("Seiryu", "Ru'Aun Gardens", 78, "Wyrm")
add_nm("Genbu", "Ru'Aun Gardens", 78, "Wyrm")
add_nm("Byakko", "Ru'Aun Gardens", 78, "Wyrm")
add_nm("Experimental Lamia", "Caedarva Mire", 78, "Lamia")
add_nm("Zareehkl the Jubilant", "Halvung", 78, "Troll")
add_nm("Marquis Naberius", "Castle Zvahl Keep", 78, "Demon")
add_nm("Ancient Goobbue", "Boyahda Tree", 78, "Goobbue")
add_nm("Giant Orobon(Fishing)", "Mount Zhayolm", 78, "Orobon")
add_nm("Northern Piranu(Fishing)", "Open sea route to Al Zahbi", 78, "Orobon")
add_nm("Gration", "Misareaux Coast", 79, "Gigas")
add_nm("Vouivre", "Ifrit's Cauldron", 79, "Wyvern")
add_nm("Leshonki", "Boyahda Tree", 79, "Sapling")
add_nm("Khimaira", "Caedarva Mire", 80, "Khimaira")
add_nm("Medusa", "Arrapago Reef", 80, "Lamia")
add_nm("Achamoth", "Halvung", 80, "Wyrm")
add_nm("Tzee Xicu the Manifest", "Den of Rancor", 80, "Yagudo")
add_nm("Shadow Lord", "Castle Zvahl Baileys", 80, "Demon")
add_nm("Dorgerwor the Astute", "Halvung", 80, "Troll")
add_nm("Garharlor the Unruly", "Mount Zhayolm", 80, "Troll")
add_nm("Energetic Eruca", "Mount Zhayolm", 80, "Crawler")
add_nm("Frostmane", "Cape Teriggan", 80, "Manticore")
add_nm("Hydra", "Wajaom Woodlands", 80, "Hydra")
add_nm("Zikko", "Caedarva Mire", 80, "Imp")
add_nm("Pelican", "Kuftal Tunnel", 80, "Cockatrice")
add_nm("Charybdis", "Sea Serpent Grotto", 80, "Sea Monk")
add_nm("Xolotl", "Attohwa Chasm", 80, "Corse")
add_nm("Bomb Queen", "Ifrit's Cauldron", 80, "Bomb")
add_nm("Sabotender Bailarina", "Quicksand Caves", 80, "Sabotender")
add_nm("Scitalis", "Grauberg (S)", 80, "Wyvern")
add_nm("Despot", "Ru'Aun Gardens", 80, "Doll")
add_nm("King Vinegarroon", "Western Altepa Desert", 80, "Scorpion")
add_nm("Ix'aern (MNK)", "Grand Palace of Hu'Xzoi", 80, "Aern")
add_nm("Big Bomb", "Halvung", 81, "Bomb")
add_nm("Bluestreak Gyugyuroon", "Aydeewa Subterrane", 82, "Qiqirn")
add_nm("Darting Kachaal Ja", "Mamook", 83, "Mamool Ja")
add_nm("Dragonscaled Bugaal Ja", "Mamook", 83, "Mamool Ja")
add_nm("Hundredfaced Hapool Ja", "Mamook", 83, "Mamool Ja")
add_nm("Zipacna", "Ve'Lugannon Palace", 83, "Golem")
add_nm("Faust", "Shrine of Ru'Avitau", 83, "Doll")
add_nm("Devout Radol Ja", "Mamook", 83, "Mamool Ja")
add_nm("Alastor Antlion", "Attohwa Chasm", 83, "Antlion")
add_nm("Shen", "Bibiki Bay - Purgonorgo Isle", 84, "Uragnite")
add_nm("Fafnir", "Dragon's Aery", 85, "Dragon")
add_nm("Nidhogg", "Dragon's Aery", 85, "Dragon")
add_nm("Tiamat", "Attohwa Chasm", 85, "Dragon")
add_nm("Vrtra", "King Ranperre's Tomb", 85, "Dragon")
add_nm("Jormungand", "Uleguerand Range", 85, "Dragon")
add_nm("Kirin", "Ru'Aun Gardens", 85, "Kirin")
add_nm("Proto-Omega", "Apollyon", 85, "Weapon")
add_nm("Proto-Ultima", "Apollyon", 85, "Weapon")
add_nm("Vulpangue", "Abyssea - Attohwa", 85, "Buffalo")
add_nm("King Behemoth", "Behemoth's Dominion", 85, "Behemoth")
add_nm("Ix'aern (MNK)", "Al'Taieu", 85, "Aern")
add_nm("Ix'aern (DRK)", "Al'Taieu", 85, "Aern")
add_nm("Ix'aern (DRG)", "Al'Taieu", 85, "Aern")
add_nm("Overlord Bakgodek", "Monastic Cavern", 85, "Orc")
add_nm("Za'Dha Adamantking", "Qulun Dome", 85, "Quadav")
add_nm("Voluptuous Vivian", "Boyahda Tree", 85, "Morbol")
add_nm("Ullikummi", "Shrine of Ru'Avitau", 85, "Golem")
add_nm("Olla Grande", "Shrine of Ru'Avitau", 85, "Magic Pot")
add_nm("Hakutaku", "Den of Rancor", 85, "Hecteyes")
add_nm("Za'Dha Adamantking", "Qulun Dome", 85, "Quadav")
add_nm("Anantaboga", "Abyssea - Attohwa", 87, "Naga")
add_nm("Dark Ixion", "West Sarutabaruta (S),East Ronfaure (S),Grauberg (S),Fort Karugo-Narugo (S),Jugner Forest (S),Rolanberry Fields (S),Batallia Downs (S)", 88, "Monoceros")

-- Level 99 Content (90-99)
add_nm("Ying", "Dynamis - Beaucedine", 90, "Demon")
add_nm("Yang", "Dynamis - Beaucedine", 90, "Demon")
add_nm("Jailer of Fortitude", "Al'Taieu", 90, "Jailer")
add_nm("Jailer of Justice", "Al'Taieu", 90, "Jailer")
add_nm("Jailer of Prudence", "Al'Taieu", 90, "Jailer")
add_nm("Arch-Omega", "Apollyon", 90, "Weapon")
add_nm("Arch-Ultima", "Apollyon", 90, "Weapon")
add_nm("Jailer of Temperance", "Al'Taieu", 90, "Jailer")
add_nm("Jailer of Love", "The Garden of Ru'Hmet", 95, "Jailer")
add_nm("Jailer of Hope", "Grand Palace of Hu'Xzoi", 95, "Jailer")
add_nm("Jailer of Faith", "Grand Palace of Hu'Xzoi", 95, "Jailer")
add_nm("Dynamis Lord", "Dynamis - Xarcabard", 99, "Demon")
add_nm("Absolute Virtue", "The Empyrean Paradox", 99, "Avatar")
add_nm("Odin", "Odin's Chamber", 99, "Avatar")
add_nm("Itzpapalotl", "Abyssea - Attohwa", 99, "Imp")
add_nm("Briareus", "Abyssea - Konschtat", 99, "Gigas")
add_nm("Sobek", "Abyssea - Grauberg", 99, "Peiste")
add_nm("Turul", "Abyssea - Uleguerand", 99, "Roc")
add_nm("Kutharei", "Abyssea - Attohwa", 99, "Wyvern")
add_nm("Cirein-croin", "Abyssea - Konschtat", 99, "Sea Monk")
add_nm("Sedna", "Abyssea - Tahrongi", 99, "Sea Monk")
add_nm("Hadhayosh", "Abyssea - Tahrongi", 99, "Buffalo")
add_nm("Apademak", "Abyssea - Tahrongi", 99, "Buffalo")
add_nm("Ulhuadshi", "Abyssea - Vunkerl", 99, "Peiste")
add_nm("Durinn", "Abyssea - Vunkerl", 99, "Dwarf")
add_nm("Maere", "Abyssea - Attohwa", 99, "Demon")
add_nm("Myrmidon Kha", "Abyssea - Konschtat", 99, "Orc")
add_nm("Bloodeye Vileberry", "Abyssea - Tahrongi", 99, "Mandragora")
add_nm("Lachrymater", "Abyssea - Konschtat", 99, "Fly")
add_nm("Triarius IV-XIV", "Abyssea - Vunkerl", 99, "Antica")
add_nm("Chloris", "Abyssea - Tahrongi", 99, "Corse")
add_nm("Glavoid", "Abyssea - Uleguerand", 99, "Worm")
add_nm("Alfard", "Abyssea - Attohwa", 99, "Hydra")
add_nm("Dragua", "Abyssea - Uleguerand", 99, "Dragon")
add_nm("Ironclad Sunderer", "Abyssea - Grauberg", 99, "Beetle")
add_nm("Flame Skimmer", "Abyssea - Grauberg", 99, "Eruca")
add_nm("Minaruja", "Abyssea - Vunkerl", 99, "Gnole")
add_nm("Ovni", "Abyssea - Tahrongi", 99, "Clionid")
add_nm("Bukhis", "Abyssea - Tahrongi", 99, "Buffalo")
add_nm("Muscaliet", "Abyssea - Grauberg", 99, "Crawlers")
add_nm("Kurma", "Abyssea - Konschtat", 99, "Adamantoise")
add_nm("Arimaspi", "Abyssea - Uleguerand", 99, "Raptors")
add_nm("Khalkotaur", "Abyssea - Konschtat", 99, "Minotaur")
add_nm("Npfundlwa", "Abyssea - Attohwa", 99, "Sandworm")
add_nm("Melo Melo", "Abyssea - Grauberg", 99, "Sea Monk")
add_nm("Berstuk", "Abyssea - Vunkerl", 99, "Gigas")
add_nm("Amphitrite", "Abyssea - Grauberg", 99, "Craklaw")
add_nm("Granite Borer", "Abyssea - Uleguerand", 99, "Worm")
add_nm("Isgebind", "Abyssea - Uleguerand", 99, "Adamantoise")
add_nm("Crocodile Dandy", "Abyssea - Grauberg", 99, "Peiste")
add_nm("Rani", "Walk of Echoes", 99, "Mantis")
add_nm("Kaggen", "Ceizak Battlegrounds", 99, "Mantis")
add_nm("Pil", "Voidwatch", 99, "Hpemde")
add_nm("Provenance Watcher", "Voidwatch", 99, "Watcher")
add_nm("Void Hare", "Voidwatch", 99, "Rabbit")
add_nm("Kumhau", "Yahse Hunting Grounds", 99, "Tiger")
add_nm("Tchakka", "Yahse Hunting Grounds", 99, "Raaz")
add_nm("Yumcax", "Yorcia Weald", 99, "Snapweed")
add_nm("Keesha Poppo", "Yorcia Weald", 99, "Poroggo")
add_nm("Mastop", "Yorcia Weald", 99, "Twitherym")
add_nm("Colkhab", "Yorcia Weald", 99, "Colkhab")
add_nm("Ng'ai", "Ceizak Battlegrounds", 99, "Snapweed")
add_nm("Brekekekex", "Ceizak Battlegrounds", 99, "Poroggo")
add_nm("Umdhlebi", "Ceizak Battlegrounds", 99, "Sabotender")
add_nm("Hurkan", "Yahse Hunting Grounds", 99, "Raaz")
add_nm("Sirrush", "Yahse Hunting Grounds", 99, "Peiste")
add_nm("Minhocao", "Yahse Hunting Grounds", 99, "Worm")
add_nm("Mellonia", "Morimar Basalt Fields", 99, "Bee")
add_nm("Cactrot Veloz", "Morimar Basalt Fields", 99, "Cactuar")
add_nm("Gasha", "Morimar Basalt Fields", 99, "Gasha")
add_nm("Otherworldly Warrior", "Foret de Hennetiel", 99, "Leafkin")
add_nm("Otherworldly Mage", "Foret de Hennetiel", 99, "Leafkin")
add_nm("Roly-Poly", "Foret de Hennetiel", 99, "Ladybug")
add_nm("Botulus Rex", "Sih Gates", 99, "Slug")
add_nm("Yallenus", "Sih Gates", 99, "Gnat")
add_nm("Alpluachra", "Marjami Ravine", 99, "Slug")
add_nm("Mauve-wristed Gomberry", "Marjami Ravine", 99, "Mandragora")
add_nm("Tiyanak", "Kamihr Drifts", 99, "Imp")
add_nm("Scylla", "Kamihr Drifts", 99, "Leech")
add_nm("Sajj'aka", "Kamihr Drifts", 99, "Twitherym")
add_nm("Akvan", "Cirdas Caverns", 99, "Chapuli")
add_nm("Dextrose", "Cirdas Caverns", 99, "Slug")
add_nm("Gestalt", "Cirdas Caverns", 99, "Clionid")
add_nm("Draketrader Zlatorog", "Outer Ra'Kaznar", 99, "Dragon")
add_nm("Palloritus", "Outer Ra'Kaznar", 99, "Clionid")
add_nm("Hurketelknafr", "Outer Ra'Kaznar", 99, "Matamata")
add_nm("Arch Dynamis Lord", "Dynamis - Xarcabard", 99, "Demon")

-- High Level Content (99+)
add_nm("Tojil", "Yorcia Weald [U]", 119, "Yorcia")
add_nm("Hapaimaru", "Morimar Basalt Fields [U]", 119, "Craklaw")
add_nm("Matamata", "Foret de Hennetiel [U]", 119, "Snapweed")
add_nm("Leafkin", "Ra'Kaznar Inner Court [U]", 119, "Mandragora")
add_nm("Sinister Reign", "Various Domains", 119, "Demon")
add_nm("Kyou", "Omen", 125, "Kyou")
add_nm("Warder of Courage", "Reisenjima", 125, "Avatar")
add_nm("Kamohoalii", "Escha - Zi'Tah", 125, "Sea Monk")
add_nm("Dhorme Khimaira", "Escha - Zi'Tah", 125, "Khimaira")
add_nm("Fleetstalker", "Escha - Zi'Tah", 125, "Manticore")
add_nm("Gullinkambi", "Escha - Zi'Tah", 125, "Cockatrice")
add_nm("Armillary Ahriman", "Escha - Zi'Tah", 125, "Ahriman")
add_nm("Onychophora", "Escha - Ru'Aun", 125, "Sandworm")
add_nm("Eschan Urn", "Escha - Ru'Aun", 125, "Urn")
add_nm("Phuabo", "Escha - Ru'Aun", 125, "Toad")
add_nm("Reisenjima Henge", "Escha - Ru'Aun", 125, "Henge")
add_nm("Kin", "Omen", 125, "Kin")
add_nm("Gin", "Omen", 125, "Gin")
add_nm("Fu", "Omen", 125, "Fu")
add_nm("Kei", "Omen", 125, "Kei")
add_nm("Pazuzu", "Escha - Zi'Tah", 128, "Demon")
add_nm("Vinipata", "Reisenjima", 128, "Panopts")
add_nm("Schah", "Reisenjima", 130, "Wraith")
add_nm("Zaffre Zurvan", "Escha - Ru'Aun", 130, "Ahriman")
add_nm("Kouryu", "Reisenjima", 135, "Dragon")
add_nm("Azi Dahaka", "Escha - Ru'Aun", 135, "Khimaira")

-- Level 99 Content (90-99)
add_nm("63 - 63", "Orobon", ??, "Orobon Lure")
add_nm("73 - 74", "Orobon", ??, "Orobon Lure")
add_nm("Arioch", "Bostaunieux Oubliette", ??, "Giant Bat")
add_nm("Manes", "Bostaunieux Oubliette", ??, "Ghost")
add_nm("Nihniknoovi", "La Theine Plateau", ??, "Bird")
add_nm("Enkelados", "Upper Delkfutt's Tower", ??, "Gigas")
add_nm("Brigandish Blade", "Ve'Lugannon Palace", ??, "Evil Weapon")
add_nm("Mother Globe", "Shrine of Ru'Avitau", ??, "Spheroid")
add_nm("Ophion", "Middle Delkfutt's Tower", ??, "Gigas")
add_nm("Polybotes", "Middle Delkfutt's Tower", ??, "Gigas")
add_nm("Rhoikos", "Middle Delkfutt's Tower", ??, "Gigas")
add_nm("Rhoitos", "Middle Delkfutt's Tower", ??, "Gigas")
add_nm("Autarch", "Upper Delkfutt's Tower", ??, "Dolls")
add_nm("Ogama", "Den of Rancor", ??, "Doomed")
add_nm("Swashstox Beadblinker", "Newton Movalpolos", ??, "Goblin")
add_nm("Aipaloovik(Fishing)", "Phanauet Channel", ??, "Pugils")
add_nm("Aiatar", "Riverne - Site A01", ??, "Wyvern")
add_nm("Imdugud", "Riverne - Site B01", ??, "Hippogryph")
add_nm("Tres Duendes", "Phomiuna Aqueducts", ??, "Bat Trio")
add_nm("Boroka", "Riverne - Site B01", ??, "Hippogryph")
add_nm("Carmine Dobsonfly", "Riverne - Site A01", ??, "Fly")
add_nm("Upyri", "Misareaux Coast", ??, "Giant Bat")
add_nm("Chariotbuster Byakzak", "Fort Ghelsba", ??, "Orc")
add_nm("Dosetsu Tree", "Qufim Island", ??, "Treant")
add_nm("Heliodromos", "Riverne - Site A01", ??, "Hippogryph")
add_nm("Mahisha", "Phomiuna Aqueducts", ??, "Tauri")
add_nm("Goblin Collector", "Newton Movalpolos", ??, "Moblin")
add_nm("Ereshkigal", "Xarcabard", ??, "Ghost")
add_nm("Shieldtrap", "Riverne - Site A01", ??, "Flytrap")
add_nm("Bugbear Matman", "Newton Movalpolos", ??, "Bugbear")
add_nm("Defoliate Leshy", "Lufaise Meadows", ??, "Treant")
add_nm("Proteus", "Silver Sea route to Nashmau", ??, "Sea Monk")
add_nm("Garfurlar the Rabid", "Mount Zhayolm", ??, "Troll")
add_nm("Garhorlur the Brutal", "Mount Zhayolm", ??, "Troll")
add_nm("Kirlirger the Abhorrent", "Halvung", ??, "Troll")
add_nm("Farlarder the Shrewd", "Halvung", ??, "Troll")
add_nm("Gurfurlur the Menacing", "Halvung", ??, "Troll")
add_nm("Bloody Bones", "Arrapago Reef", ??, "Skeleton")
add_nm("Southern Piranu(Fishing)", "Open sea route to Al Zahbi", ??, "Orobon")
add_nm("Almighty Apkallu", "Silver Sea route to Al Zahbi", ??, "Apkallu")
add_nm("Crystal Eater", "Aydeewa Subterrane", ??, "Funguar")
add_nm("Zizzy Zillah", "Mamook", ??, "Cockatrice")
add_nm("Gulool Ja Ja", "Mamook", ??, "Mamool Ja")
add_nm("Ravin Raven", "Caedarva Mire", ??, "Bird")
add_nm("Vulkodlac", "Jugner Forest (S)", ??, "Gnole")
add_nm("Cyclopean Conch(Fishing)", "Manaclipper", ??, "Uragnites")
add_nm("Harajnite(Fishing)", "Manaclipper", ??, "Uragnites")

-- Helper functions
function nm_database.is_nm(name)
    if not name then return false end
    return nm_database.nm_set[name:lower()] == true
end

function nm_database.get_details(name)
    if not name then return nil end
    return nm_database.nm_details[name:lower()]
end

function nm_database.get_count()
    local count = 0
    for _ in pairs(nm_database.nm_set) do
        count = count + 1
    end
    return count
end

return nm_database
