-- Missions
-- Auto-generated from bg-wiki

local missions = {
    {
      id = "mission_toau_1",
      name = "Aht Urhgan Mission 1",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 1,
      game_id = 0,
      repeatable = false,
      steps = {
        "Complete the quest The Road to Aht Urhgan .",
        "Head to Mhaura and take the boat to Aht Urhgan Whitegate . If you choose to pay 500,000 gil you do not need to take the boat to start the mission. You no longer need to take the boat at all as the Unity Warp for Wajaom Woodlands (lv. 125) will take you to a good location to make a brief trek on foot. The survival guide for Aydeewa Subterrane is just inside where it warps you. This becomes available as soon as you get the Boarding permit , along with the warp to Mount Zhayolm .",
        "Approach Naja Salaheem at (I-10) to receive the Supplies package . She is located inside the building upstairs in the northeast corner of the grid square.",
        "If this is your first time to Aht Urhgan Whitegate , be sure to pick up the Home Point crystal (to make future travel easier). There is a residential zone pretty close to where you exit the ferry dock. There is a Home Point crystal there.",
        "If you choose to pay 500,000 gil you do not need to take the boat to start the mission.",
        "You no longer need to take the boat at all as the Unity Warp for Wajaom Woodlands (lv. 125) will take you to a good location to make a brief trek on foot. The survival guide for Aydeewa Subterrane is just inside where it warps you. This becomes available as soon as you get the Boarding permit , along with the warp to Mount Zhayolm .",
        "The survival guide for Aydeewa Subterrane is just inside where it warps you.",
        "This becomes available as soon as you get the Boarding permit , along with the warp to Mount Zhayolm .",
        "She is located inside the building upstairs in the northeast corner of the grid square.",
        "There is a residential zone pretty close to where you exit the ferry dock. There is a Home Point crystal there.",
      }
    },
    {
      id = "mission_toau_2",
      name = "Aht Urhgan Mission 2",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 2,
      game_id = 0,
      repeatable = false,
      steps = {
        "PSC Wildcat Badge",
        "150 Imperial Standing",
        "Mog Locker Access",
        "Sanction",
        "Completing this mission grants access to the Mog Locker .",
        "Completing this mission grants access use the Runic Portal .",
        "Completing this mission grants access to Assault",
        "Take the Supplies package to any one of the Staging Points (with the exception of Nyzul Isle Staging Point and the Aht Urhgan Whitegate portal, Chamber of Passage ), and talk to the NPC stationed there to complete delivery. Once you're at a staging point, be sure to do the delivery first to the nearby NPC, as interacting with the Runic Portal will teleport you directly back to Aht Urhgan Whitegate , and you will not be allowed to use the Chamber of Passage to return yet. Visit the Staging Points page by clicking here and then click on one of the Runic Portal Names for detailed steps on reaching one of these locations. You will eventually want them all, so pick any of them. Note for returners and new players: there's now another quick way to initially get to Nashmau (without taking the Ferry or navigating Alzadaal teleporters ) via a Voidwatch Warp easily available to most players using the Caedarva Mire destination. (There's no easily unlockable Unity warp for that purpose!) At H-10 in Aht Urhgan Whitegate there's a tunnel on the first floor where you'll find an Ironbound Gate , which leads outside to Wajaom Woodlands Postern where you can talk to Camille to Participate in Voidwatch Ops. You don't need to have done any other part of Voidwatch at all - you just need to be level 75 and be Rank 3 in your home nation. After receiving the Amber stratum abyssite , you can now use any Atmacite Refiner (in the Present) to warp to these locations initially to unlock other Home Points, Survival Guides, and Staging Points (hence the inclusion in this section!)... you'll just need 1000 cruor . If you don't have cruor from Abyssea , you can exchange 1 copper voucher from a Sparks NPC for the fee – and in Southern San d'Oria or Bastok Markets this is right next to the Atmacite Refiner at those locations. And, from the Atmacite Refiner , do Request Teleportation –> Aht Urhgan. –> Caedarva Mire. , and you'll be just outside the east entrance of Nashmau . Walk inside to grab the Survival Guide and the Home Point and continue your journey. From here, the Azouph Isle Staging Point is very close with a mount. You can use either the east or north exit from Nashmau to get there.",
        "After you've delivered the Supplies package to the blue-clad Immortal NPC nearby, use the Runic Portal at the Staging Point to return to Aht Urhgan Whitegate .",
        "Speak to Naja Salaheem .",
        "Once you're at a staging point, be sure to do the delivery first to the nearby NPC, as interacting with the Runic Portal will teleport you directly back to Aht Urhgan Whitegate , and you will not be allowed to use the Chamber of Passage to return yet.",
        "Visit the Staging Points page by clicking here and then click on one of the Runic Portal Names for detailed steps on reaching one of these locations. You will eventually want them all, so pick any of them. Note for returners and new players: there's now another quick way to initially get to Nashmau (without taking the Ferry or navigating Alzadaal teleporters ) via a Voidwatch Warp easily available to most players using the Caedarva Mire destination. (There's no easily unlockable Unity warp for that purpose!) At H-10 in Aht Urhgan Whitegate there's a tunnel on the first floor where you'll find an Ironbound Gate , which leads outside to Wajaom Woodlands Postern where you can talk to Camille to Participate in Voidwatch Ops. You don't need to have done any other part of Voidwatch at all - you just need to be level 75 and be Rank 3 in your home nation. After receiving the Amber stratum abyssite , you can now use any Atmacite Refiner (in the Present) to warp to these locations initially to unlock other Home Points, Survival Guides, and Staging Points (hence the inclusion in this section!)... you'll just need 1000 cruor . If you don't have cruor from Abyssea , you can exchange 1 copper voucher from a Sparks NPC for the fee – and in Southern San d'Oria or Bastok Markets this is right next to the Atmacite Refiner at those locations. And, from the Atmacite Refiner , do Request Teleportation –> Aht Urhgan. –> Caedarva Mire. , and you'll be just outside the east entrance of Nashmau . Walk inside to grab the Survival Guide and the Home Point and continue your journey. From here, the Azouph Isle Staging Point is very close with a mount. You can use either the east or north exit from Nashmau to get there.",
        "Note for returners and new players: there's now another quick way to initially get to Nashmau (without taking the Ferry or navigating Alzadaal teleporters ) via a Voidwatch Warp easily available to most players using the Caedarva Mire destination. (There's no easily unlockable Unity warp for that purpose!) At H-10 in Aht Urhgan Whitegate there's a tunnel on the first floor where you'll find an Ironbound Gate , which leads outside to Wajaom Woodlands Postern where you can talk to Camille to Participate in Voidwatch Ops. You don't need to have done any other part of Voidwatch at all - you just need to be level 75 and be Rank 3 in your home nation. After receiving the Amber stratum abyssite , you can now use any Atmacite Refiner (in the Present) to warp to these locations initially to unlock other Home Points, Survival Guides, and Staging Points (hence the inclusion in this section!)... you'll just need 1000 cruor . If you don't have cruor from Abyssea , you can exchange 1 copper voucher from a Sparks NPC for the fee – and in Southern San d'Oria or Bastok Markets this is right next to the Atmacite Refiner at those locations. And, from the Atmacite Refiner , do Request Teleportation –> Aht Urhgan. –> Caedarva Mire. , and you'll be just outside the east entrance of Nashmau . Walk inside to grab the Survival Guide and the Home Point and continue your journey. From here, the Azouph Isle Staging Point is very close with a mount. You can use either the east or north exit from Nashmau to get there.",
        "At H-10 in Aht Urhgan Whitegate there's a tunnel on the first floor where you'll find an Ironbound Gate , which leads outside to Wajaom Woodlands Postern where you can talk to Camille to Participate in Voidwatch Ops. You don't need to have done any other part of Voidwatch at all - you just need to be level 75 and be Rank 3 in your home nation.",
        "After receiving the Amber stratum abyssite , you can now use any Atmacite Refiner (in the Present) to warp to these locations initially to unlock other Home Points, Survival Guides, and Staging Points (hence the inclusion in this section!)... you'll just need 1000 cruor .",
        "If you don't have cruor from Abyssea , you can exchange 1 copper voucher from a Sparks NPC for the fee – and in Southern San d'Oria or Bastok Markets this is right next to the Atmacite Refiner at those locations.",
        "And, from the Atmacite Refiner , do Request Teleportation –> Aht Urhgan. –> Caedarva Mire. , and you'll be just outside the east entrance of Nashmau . Walk inside to grab the Survival Guide and the Home Point and continue your journey.",
        "From here, the Azouph Isle Staging Point is very close with a mount. You can use either the east or north exit from Nashmau to get there.",
      }
    },
    {
      id = "mission_toau_3",
      name = "Aht Urhgan Mission 3",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 3,
      game_id = 0,
      repeatable = false,
      steps = {
        "You must zone out and return to get the cutscenes. There is an exit to Wajaom Woodlands west of the office under the stairs.",
        "Speak to Rytaal (K-10) for an explanation of Assault . This also unlocks access to it. Rytaal is located in the Commissions Agency through the door in (K-9).",
        "Speak to Naja Salaheem twice for two cutscenes to finish this mission and immediately begin the next.",
        "There is an exit to Wajaom Woodlands west of the office under the stairs.",
        "Rytaal is located in the Commissions Agency through the door in (K-9).",
        "(Optional) Speak to Fubruhn (F-11) regarding Mog Locker upgrades, administration, and accessibility.",
        "If you have completed RoV Mission 2-7 - Ever Forward , you may speak to Abquhbah after this mission to receive his Trust cipher.",
      }
    },
    {
      id = "mission_toau_4",
      name = "Aht Urhgan Mission 4",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 4,
      game_id = 0,
      repeatable = false,
      steps = {
        "This mission begins immediately after the previous cutscene.",
        "Speak to Cacaroon (G-11) for a cutscene, across from the Mog House.",
        "Trade Cacaroon 1,000 gil or one Imperial Bronze Piece for another cutscene. If you chose to pay the gil instead of giving the coin, he won't automatically take the gil from you. You have to trade it to him.",
        "Enter the Walahra Temple (K-8) for another cutscene.",
        "Head to the Shararat Teahouse (K-12) for another cutscene.",
        "Answer the following questions to complete the quest.",
        "If you chose to pay the gil instead of giving the coin, he won't automatically take the gil from you. You have to trade it to him.",
        "What have you learned about? Pick all 3.",
        "Same as first question but with a new answer. Raillefal's secret.",
        "You are really... A San d'Orian Prince.",
        "Raillefal is really... Prince Trion.",
      }
    },
    {
      id = "mission_toau_5",
      name = "Aht Urhgan Mission 5",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 5,
      game_id = 0,
      repeatable = false,
      steps = {
        "Enter Chateau d'Oraguille from Northern San d'Oria (I-6).",
        "Speak to Halver (I-9).",
      }
    },
    {
      id = "mission_toau_6",
      name = "Aht Urhgan Mission 6",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 6,
      game_id = 0,
      repeatable = false,
      steps = {
        "Note: You must wait one Earth minute after completing the previous quest to begin this quest.",
        "Approach the Palace in Ru'Lude Gardens for a cutscene.",
        "Choose any of the answers to the questions to complete the quest. Choosing \"Yes\", followed by \"That's what I'm here for!\" will reward you with 10 Imperial Bronze Pieces . Choosing \"What am I, a donkey?\" will complete the quest but forfeit 10x Imperial Bronze Piece",
        "Choosing \"Yes\", followed by \"That's what I'm here for!\" will reward you with 10 Imperial Bronze Pieces .",
        "Choosing \"What am I, a donkey?\" will complete the quest but forfeit 10x Imperial Bronze Piece",
      }
    },
    {
      id = "mission_toau_7",
      name = "Aht Urhgan Mission 7",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 7,
      game_id = 0,
      repeatable = false,
      steps = {
        "Raillefal's note",
        "Imperial Silver Piece x2",
        "Head to the Shararat Teahouse (K-11) for a cutscene. You will obtain Raillefal's note The choices have no effect on the mission. Choose whatever answer you like best. You'll be given a Imperial Silver Piece at the conclusion of the cutscene.",
        "Speak to Naja Salaheem (I-10) for a cutscene. You'll be given the second Imperial Silver Piece at the conclusion of the cutscene. If you are asked for an Imp Wing , it is due to the Promotion: Private First Class quest. Simply trade one to continue.",
        "The choices have no effect on the mission. Choose whatever answer you like best.",
        "You'll be given a Imperial Silver Piece at the conclusion of the cutscene.",
        "You'll be given the second Imperial Silver Piece at the conclusion of the cutscene.",
        "If you are asked for an Imp Wing , it is due to the Promotion: Private First Class quest. Simply trade one to continue.",
      }
    },
    {
      id = "mission_toau_8",
      name = "Aht Urhgan Mission 8",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 8,
      game_id = 0,
      repeatable = false,
      steps = {
        "Zone, and return to Salaheem's Sentinels (I-10) for a cutscene.",
      }
    },
    {
      id = "mission_toau_9",
      name = "Aht Urhgan Mission 9",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 9,
      game_id = 0,
      repeatable = false,
      steps = {
        "Astral compass",
        "If you have not yet unlocked the Runic Portal at the Nyzul Isle Staging Point :",
        "Trade one Imperial Silver Piece to Kamih Mapokhalam (F-6) located in Bhaflau Thickets on Map 1. (Optional) Trade Kamih Mapokhalam 3 Imperial Mythril Pieces for a map of the Alzadaal Undersea Ruins . This map is now purchasable via the Magical Map vendors.",
        "(Optional) Trade Kamih Mapokhalam 3 Imperial Mythril Pieces for a map of the Alzadaal Undersea Ruins . This map is now purchasable via the Magical Map vendors.",
        "This map is now purchasable via the Magical Map vendors.",
        "Alternative Option , if you've unlocked quick transportation to Nashmau , you can head out of the east entrance for a shorter trek, with the Imperial guard Tyamah at (J-10) of Caedarva Mire . Trade him a Imperial Silver Piece to proceed.",
        "Approach the Gilded Doors (H-8) on Map 7 for a cutscene.",
        "Unlock the Runic Portal at the Nyzul Isle Staging Point before departing. This is one of the most frequently-used Runic Portals in Whitegate. Enter the Gilded Doors and take the transporter to the left. Caution: Stay left behind Gilded Doors , Apex Gears (145-147) are to the right. Now map 3, take the portal on your left again. (You'll end up on the main map.) Exit the room to the south and follow the path east until the \"Gilded Doors\". Once opened, keep going east until you reach the \"Gilded Doors\" to the Nyzul Isle Staging Point .",
        "This is one of the most frequently-used Runic Portals in Whitegate.",
        "Enter the Gilded Doors and take the transporter to the left. Caution: Stay left behind Gilded Doors , Apex Gears (145-147) are to the right.",
        "Now map 3, take the portal on your left again. (You'll end up on the main map.)",
        "Exit the room to the south and follow the path east until the \"Gilded Doors\". Once opened, keep going east until you reach the \"Gilded Doors\" to the Nyzul Isle Staging Point .",
        "If you have already unlocked it:",
        "Enter the Chamber of Passage and take the Runic Portal to the Nyzul Isle Staging Point .",
        "Take the southeastern transport device at (H-9) to get to the Bhaflau Remnants .",
        "Take the right (eastern) transport device to get to the Alzadaal Undersea Ruins .",
        "The cutscene will start when you zone in.",
      }
    },
    {
      id = "mission_toau_10",
      name = "Aht Urhgan Mission 10",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 10,
      game_id = 0,
      repeatable = false,
      steps = {
        "Return to Naja Salaheem (I-10) for a cutscene.",
      }
    },
    {
      id = "mission_toau_11",
      name = "Aht Urhgan Mission 11",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 11,
      game_id = 0,
      repeatable = false,
      steps = {
        "Wait a game day and zone then return to Naja Salaheem .",
      }
    },
    {
      id = "mission_toau_12",
      name = "Aht Urhgan Mission 12",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 12,
      game_id = 0,
      repeatable = false,
      steps = {
        "Note: You must wait one game day and zone after completing the previous mission.",
        "Once you start this mission, you can progress past the Rhapsodies of Vana'diel mission Ever Forward .",
        "Head to Salaheem's Sentinels ( Aht Urhgan Whitegate I-10) for a cutscene.",
        "Speak to Pyopyoroon ( Nashmau H-7) who asks for Jody's Acid . Jody's Acid drops off Ameretats in Bhaflau Thickets and Wajaom Woodlands , and from Great Ameretats in Wajaom Woodlands and Aydeewa Subterrane .",
        "Trade Jody's Acid to Pyopyoroon to receive a Vial of spectral scent .",
        "Jody's Acid drops off Ameretats in Bhaflau Thickets and Wajaom Woodlands , and from Great Ameretats in Wajaom Woodlands and Aydeewa Subterrane .",
      }
    },
    {
      id = "mission_toau_13",
      name = "Aht Urhgan Mission 13",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 13,
      game_id = 0,
      repeatable = false,
      steps = {
        "Head to Caedarva Mire from the west exit in Nashmau and examine Jazaratt's Headstone at (E-10). Southeast of Caedarva Mire HP#1",
        "Check the headstone again to spawn a Fomor NM Jazaraat .",
        "Check Jazaraat's Headstone a third time to receive an Ephramadian gold coin .",
        "Southeast of Caedarva Mire HP#1",
        "Note: There is a battle approaching in the next two missions. If you want another player to participate (who has already completed battle) they must also have this coin. All the other player needs to do is touch the headstone.",
      }
    },
    {
      id = "mission_toau_14",
      name = "Aht Urhgan Mission 14",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 14,
      game_id = 0,
      repeatable = false,
      steps = {
        "Return to Naja Salaheem for a cutscene. After this cutscene you will automatically be on the next mission, The Black Coffin.",
      }
    },
    {
      id = "mission_toau_15",
      name = "Aht Urhgan Mission 15",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 15,
      game_id = 0,
      repeatable = false,
      steps = {
        "Head to the Cutter, which is located at (H-8) on Map 5 of Arrapago Reef .",
        "The faster route, provided you already have the teleport unlocked. Requires running through most of Arrapago Reef .",
        "Take the Survival Guide to Caedarva Mire and run south to zone into Arrapago Reef at (G-8). Note this is NOT the (G-6) zone to Arrapago Reef just east of where you teleport in from the Survival Guide",
        "After zoning, head south to (H-8 on Map 5) to find the Cutter.",
        "Requires running through most of Arrapago Reef .",
        "Note this is NOT the (G-6) zone to Arrapago Reef just east of where you teleport in from the Survival Guide",
        "Travel to Dvucca Isle Staging Point . Requires an Imperial Silver Piece (or just 200 Standing) to reach if your Assault Rank is lower than Captain . See directions here .",
        "You may instead walk to this Staging Point from the teleport to Nyzul Isle Staging Point if you prefer. Take the northwest teleporter at (G-8) out to Arrapago Remnants, then the west teleport from there, and exit.",
        "Head west to (F-9)(entrance 3) and zone into Arrapago Reef .",
        "After zoning, head north to (H-8 on Map 5) to find the Cutter.",
        "Requires an Imperial Silver Piece (or just 200 Standing) to reach if your Assault Rank is lower than Captain . See directions here .",
        "Approach the Cutter for a cutscene.",
        "When you are ready, Examine the Cutter to enter a battlefield.",
        "All members of your party (including any who have finished this mission before) need an Ephramadian gold coin to enter the battlefield. If you need another gold coin, examine Jazaraat's Headstone at Caedarva Mire (E-10).",
        "Gessho will assist you in this fight. Gessho will wait a minute or two before he begins to fight. This gives your party a little time to buff. The fight will continue in the event Gessho is killed.",
        "The battle is against the Ashu Talif Crew which consists of 2x Rangers , 2x Red Mages , and 1x Corsair . The Ashu Talif Crew seem to be resistant to most forms of sleep unless Elemental Seal is used first. Lullaby was easily landed in Item Level 119 equipment.",
        "Once the five Ashu Talif Crew members are defeated, another four will take their place.",
        "The Ashu Talif Captain will spawn along with the others.",
        "You must bring the Ashu Talif Captain 's health to approximately 20% to win the battle.",
        "After the fight, you will wind up in Nashmau . Players who have already completed this mission will end up back at the Cutter instead.",
        "If you need another gold coin, examine Jazaraat's Headstone at Caedarva Mire (E-10).",
        "Gessho will wait a minute or two before he begins to fight. This gives your party a little time to buff.",
        "The fight will continue in the event Gessho is killed.",
        "The Ashu Talif Crew seem to be resistant to most forms of sleep unless Elemental Seal is used first.",
        "Lullaby was easily landed in Item Level 119 equipment.",
        "Players who have already completed this mission will end up back at the Cutter instead.",
      }
    },
    {
      id = "mission_toau_16",
      name = "Aht Urhgan Mission 16",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 16,
      game_id = 0,
      repeatable = false,
      steps = {
        "Back at Aht Urhgan Whitegate , speak to Naja Salaheem for a cutscene.",
      }
    },
    {
      id = "mission_toau_17",
      name = "Aht Urhgan Mission 17",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 17,
      game_id = 0,
      repeatable = false,
      steps = {
        "Speak to Naja Salaheem for a cutscene.",
        "Play dress up with Naja Salaheem .",
        "Before you can continue, Naja Salaheem will ask that you wear something more appropriate to the palace.",
        "Make sure to speak with her again after playing dress up with her and wearing the armor listed below otherwise you won't get the CS at the palace. In addition to the listed armor, you must also be wearing gloves, leg armor, and boots. They do not however, have to match anything else you are wearing. Gear that prevents the player from equipping gear in another slot (sometimes referred to as \"occupying multiple slots\" or \"multi-slot gear\") does not count as wearing gear in the prohibited slots. Wearing the following armors are known to allow you to continue. Hover a name to see the job level requirements, and click on the image to check the Auction House stock (Be sure to set your server on the top left of FFXIAH.com if you haven't): Adaman Cuirass Aketon Amir Korazin Arhat's Gi Barone Corazza Black Cloak Black Cotehardie Blessed Bliaut Bloody Aketon Blue Cotehardie Byrnie Brigandine Can be obtained for free via RoE - Conflict: Beadeaux Cardinal Vest Chasuble Dusk Jerkin Dragon Harness Errant Houppelande Hachiman Domaru Haubergeon Hauberk Holy Breastplate Homam Corazza Igqira Weskit Jaridah Peti Justaucorps Nashira Manteel Noble's Tunic Pahluwan Khazagand Plastron Rasetsu Samue Scorpion Harness Sipahi Jawshan Sha'ir Manteel Vermillion Cloak Yigit Gomlek",
        "Check the Imperial Whitegate door at (L-8) in Aht Urhgan Whitegate with the proper attire and your weapons removed for a cutscene, after which you will receive an Imperial Mythril Piece . Note: Confirm that you have space in your inventory before watching the cutscene, or you'll have to make space and watch the entire scene again if you do not obtain your reward.",
        "In addition to the listed armor, you must also be wearing gloves, leg armor, and boots. They do not however, have to match anything else you are wearing. Gear that prevents the player from equipping gear in another slot (sometimes referred to as \"occupying multiple slots\" or \"multi-slot gear\") does not count as wearing gear in the prohibited slots.",
        "Wearing the following armors are known to allow you to continue. Hover a name to see the job level requirements, and click on the image to check the Auction House stock (Be sure to set your server on the top left of FFXIAH.com if you haven't): Adaman Cuirass Aketon Amir Korazin Arhat's Gi Barone Corazza Black Cloak Black Cotehardie Blessed Bliaut Bloody Aketon Blue Cotehardie Byrnie Brigandine Can be obtained for free via RoE - Conflict: Beadeaux Cardinal Vest Chasuble Dusk Jerkin Dragon Harness Errant Houppelande Hachiman Domaru Haubergeon Hauberk Holy Breastplate Homam Corazza Igqira Weskit Jaridah Peti Justaucorps Nashira Manteel Noble's Tunic Pahluwan Khazagand Plastron Rasetsu Samue Scorpion Harness Sipahi Jawshan Sha'ir Manteel Vermillion Cloak Yigit Gomlek",
        "Gear that prevents the player from equipping gear in another slot (sometimes referred to as \"occupying multiple slots\" or \"multi-slot gear\") does not count as wearing gear in the prohibited slots.",
        "Adaman Cuirass",
        "Aketon",
        "Amir Korazin",
        "Arhat's Gi",
        "Barone Corazza",
        "Black Cloak",
        "Black Cotehardie",
        "Blessed Bliaut",
        "Bloody Aketon",
        "Blue Cotehardie",
        "Byrnie",
        "Brigandine Can be obtained for free via RoE - Conflict: Beadeaux",
        "Cardinal Vest",
        "Chasuble",
        "Dusk Jerkin",
        "Dragon Harness",
        "Errant Houppelande",
        "Hachiman Domaru",
        "Haubergeon",
        "Hauberk",
        "Holy Breastplate",
        "Homam Corazza",
        "Igqira Weskit",
        "Jaridah Peti",
        "Justaucorps",
        "Nashira Manteel",
        "Noble's Tunic",
        "Pahluwan Khazagand",
        "Plastron",
        "Rasetsu Samue",
        "Scorpion Harness",
        "Sipahi Jawshan",
        "Sha'ir Manteel",
        "Vermillion Cloak",
        "Yigit Gomlek",
        "Can be obtained for free via RoE - Conflict: Beadeaux",
        "Note: Confirm that you have space in your inventory before watching the cutscene, or you'll have to make space and watch the entire scene again if you do not obtain your reward.",
      }
    },
    {
      id = "mission_toau_18",
      name = "Aht Urhgan Mission 18",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 18,
      game_id = 0,
      repeatable = false,
      steps = {
        "Unlock Ashu Talif Assault",
        "Note: You must wait one game day and zone after completing the previous mission before you can receive this cutscene.",
        "Approach Naja Salaheem for a cutscene.",
        "Optional: After completing the mission, you will be eligible for Ashu Talif Assault .",
        "After completing this mission, you may examine the cushion in Aht Urhgan Whitegate (J-12) to acquire Cipher: Gessho .",
      }
    },
    {
      id = "mission_toau_19",
      name = "Aht Urhgan Mission 19",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 19,
      game_id = 0,
      repeatable = false,
      steps = {
        "Enter the Shararat Teahouse in Aht Urhgan Whitegate for a cutscene.",
      }
    },
    {
      id = "mission_toau_20",
      name = "Aht Urhgan Mission 20",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 20,
      game_id = 0,
      repeatable = false,
      steps = {
        "Head to Aydeewa Subterrane via one of the routes below. Via Wajaom Woodlands - Head to (G-7) in Wajaom Woodlands . Survival Guide - Take the guide to Aydeewa Subterrane . Unity Warp - Take the CL135 Wajaom Woodlands or CL145 Aydeewa Subterrane warp. The entrance is directly behind you if you took the CL135 warp.",
        "After the cutscene, continue further into the Subterrane until you find a room with two exits at (E-9/F-9) in the southwest part of this map. Monsters in this part of the Subterrane are 70+ and will aggro, so be sure you have Sneak and Invisible on.",
        "Head west down the ramp which takes you to the western portion of Aydeewa Subterrane (Map 5).",
        "At (F-8/G-8) there is a blank target you need to check for a cutscene.",
        "The mission is finished once you watch the cutscene.",
        "Via Wajaom Woodlands - Head to (G-7) in Wajaom Woodlands .",
        "Survival Guide - Take the guide to Aydeewa Subterrane .",
        "Unity Warp - Take the CL135 Wajaom Woodlands or CL145 Aydeewa Subterrane warp. The entrance is directly behind you if you took the CL135 warp.",
        "The entrance is directly behind you if you took the CL135 warp.",
        "Monsters in this part of the Subterrane are 70+ and will aggro, so be sure you have Sneak and Invisible on.",
      }
    },
    {
      id = "mission_toau_21",
      name = "Aht Urhgan Mission 21",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 21,
      game_id = 0,
      repeatable = false,
      steps = {
        "Enter Salaheem's Sentinels for a cutscene.",
      }
    },
    {
      id = "mission_toau_22",
      name = "Aht Urhgan Mission 22",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 22,
      game_id = 0,
      repeatable = false,
      steps = {
        "Travel to Navukgo Execution Chamber . The Mount Zhayolm Home Point will take you right outside the zone. (Use Unity Warp > 135 > Mount Zhayolm if you do not have the Home Point ) The Unity Warp will place you a short walk away from the zone. After arriving in Mount Zhayolm , immediately turn around. Head forward, then take the East junction at the (C-7)/(C-8) line. You can use your Map to locate the Home Point quickly.",
        "You will get a cutscene when you first enter Navukgo Execution Chamber .",
        "Examine the Decorative Bronze Gate for another cutscene.",
        "Examine the gate once more to enter a battlefield.",
        "The fight is against Khimaira 13 .",
        "Khimaira 13 uses the following special attacks: Dreadstorm : AoE DMG + terrorize. Removes Utsusemi . Tenebrous Mist : TP is reset to 0. Thunderstrike : AoE DMG + Stun . Removes Utsusemi . Tourbillion : AoE DMG + Knockback. Removes Utsusemi .",
        "Lady Karababa will assist you in this fight. She uses various high level spells and casts them much faster than players can. She seems to prefer Ancient Magic II spells. If her health drops too low and she has not been healed, she will Warp from the battlefield resulting in a loss.",
        "The Mount Zhayolm Home Point will take you right outside the zone. (Use Unity Warp > 135 > Mount Zhayolm if you do not have the Home Point ) The Unity Warp will place you a short walk away from the zone. After arriving in Mount Zhayolm , immediately turn around. Head forward, then take the East junction at the (C-7)/(C-8) line. You can use your Map to locate the Home Point quickly.",
        "The Unity Warp will place you a short walk away from the zone. After arriving in Mount Zhayolm , immediately turn around. Head forward, then take the East junction at the (C-7)/(C-8) line. You can use your Map to locate the Home Point quickly.",
        "Dreadstorm : AoE DMG + terrorize. Removes Utsusemi .",
        "Tenebrous Mist : TP is reset to 0.",
        "Thunderstrike : AoE DMG + Stun . Removes Utsusemi .",
        "Tourbillion : AoE DMG + Knockback. Removes Utsusemi .",
        "She uses various high level spells and casts them much faster than players can. She seems to prefer Ancient Magic II spells.",
        "If her health drops too low and she has not been healed, she will Warp from the battlefield resulting in a loss.",
      }
    },
    {
      id = "mission_toau_23",
      name = "Aht Urhgan Mission 23",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 23,
      game_id = 0,
      repeatable = false,
      steps = {
        "Enter Salaheem's Sentinels for a cutscene.",
      }
    },
    {
      id = "mission_toau_24",
      name = "Aht Urhgan Mission 24",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 24,
      game_id = 0,
      repeatable = false,
      steps = {
        "Enter Salaheem's Sentinels again after zoning and one game day has passed.",
      }
    },
    {
      id = "mission_toau_25",
      name = "Aht Urhgan Mission 25",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 25,
      game_id = 0,
      repeatable = false,
      steps = {
        "Speak to Naja Salaheem again after zoning and one game day has passed for a cutscene.",
        "Choosing Aphmau in the cutscene will continue the mission.",
      }
    },
    {
      id = "mission_toau_26",
      name = "Aht Urhgan Mission 26",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 26,
      game_id = 0,
      repeatable = false,
      steps = {
        "Unequip your weapon and examine the Imperial Whitegate door at (L-9) in Aht Urhgan Whitegate .",
      }
    },
    {
      id = "mission_toau_27",
      name = "Aht Urhgan Mission 27",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 27,
      game_id = 0,
      repeatable = false,
      steps = {
        "Head to Aydeewa Subterrane via one of the routes below. Via Wajaom Woodlands - Head to (G-7) in Wajaom Woodlands . Survival Guide - Take the guide to Aydeewa Subterrane . Unity Warp - Take the CL135 Wajaom Woodlands or CL145 Aydeewa Subterrane warp. The entrance is directly behind you if you took the CL135 warp.",
        "Continue further into the Subterrane until you find a room in the southwest at (E-9/F-9).",
        "Head west down the ramp which will take you to the western portion of Aydeewa Subterrane (Map 5).",
        "At (F-8/G-8) there is a blank target you need to check for a cutscene. This is the same location from Aht Urhgan Mission 20 . Monsters in this part of the Subterrane aggro, so be sure you have Sneak and Invisible on.",
        "The mission is finished once you watch the cutscene.",
        "Via Wajaom Woodlands - Head to (G-7) in Wajaom Woodlands .",
        "Survival Guide - Take the guide to Aydeewa Subterrane .",
        "Unity Warp - Take the CL135 Wajaom Woodlands or CL145 Aydeewa Subterrane warp. The entrance is directly behind you if you took the CL135 warp.",
        "The entrance is directly behind you if you took the CL135 warp.",
        "Monsters in this part of the Subterrane aggro, so be sure you have Sneak and Invisible on.",
      }
    },
    {
      id = "mission_toau_28",
      name = "Aht Urhgan Mission 28",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 28,
      game_id = 0,
      repeatable = false,
      steps = {
        "Enter the Walahra Temple in Aht Urhgan Whitegate for a cutscene.",
      }
    },
    {
      id = "mission_toau_29",
      name = "Aht Urhgan Mission 29",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 29,
      game_id = 0,
      repeatable = false,
      steps = {
        "After the last mission's cutscene is over, you will need to head to Jade Sepulcher . It is recommended that you use Homepoint #1 to Bhaflau Thickets . If you don't have the Homepoint, go to Mamool Ja Staging Point . Once you take the staging point, head north to the Jade Sepulcher zoneline located at (I-9). You will need both Sneak and Invisible (Status) . (Or a mount)",
        "Examine the Ornamental Door for a cutscene.",
        "Check the door again and select \"Puppet in Peril\" to enter the battlefield.",
        "The fight is against Lancelord Gaheel Ja . Lancelord Gaheel Ja is a Paladin and can use spells such as Flash , Holy , Cure - Cure IV . Lancelord Gaheel Ja can use the following abilities: Clobber : Large radius AoE DMG. Granite Skin : Stoneskin effect that cannot be dispelled. All attacks to the front of him will have no effect, but attacks done behind him will. This effects wears quickly. Blazing Angon : AoE DMG centered around his target.",
        "Upon winning the battle, you will automatically watch another cutscene that completes this mission.",
        "It is recommended that you use Homepoint #1 to Bhaflau Thickets .",
        "If you don't have the Homepoint, go to Mamool Ja Staging Point . Once you take the staging point, head north to the Jade Sepulcher zoneline located at (I-9). You will need both Sneak and Invisible (Status) . (Or a mount)",
        "You will need both Sneak and Invisible (Status) . (Or a mount)",
        "Lancelord Gaheel Ja is a Paladin and can use spells such as Flash , Holy , Cure - Cure IV .",
        "Lancelord Gaheel Ja can use the following abilities: Clobber : Large radius AoE DMG. Granite Skin : Stoneskin effect that cannot be dispelled. All attacks to the front of him will have no effect, but attacks done behind him will. This effects wears quickly. Blazing Angon : AoE DMG centered around his target.",
        "Clobber : Large radius AoE DMG.",
        "Granite Skin : Stoneskin effect that cannot be dispelled. All attacks to the front of him will have no effect, but attacks done behind him will. This effects wears quickly.",
        "Blazing Angon : AoE DMG centered around his target.",
      }
    },
    {
      id = "mission_toau_30",
      name = "Aht Urhgan Mission 30",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 30,
      game_id = 0,
      repeatable = false,
      steps = {
        "Zone into Arrapago Reef for a cutscene first. Best route as of the August 2025 Version Update: Purchase an Arrapago Ring with 100 Imperial standing accolades from Asrahd at Aht Urhgan Whitegate (I-8). This will put you very close to the next step of the mission as well. Option 1, use the Survival Guide in Caedarva Mire and head North / Northwest before turning South to the Arrapago Reef (4) entrance. Option 2, use Dvucca Isle Staging Point and use the Caedarva Mire map #2 to zone into the Arrapago Reef (3) off-map/hidden G-9 entrance. Option 3, use the Ilrusi Atoll Staging Point to receive the initial cutscene, but may be further from the Cutter for the remaining mission requirements. Option 4, go to the Survival Guide in Arrapago Reef directly for the cutscene, but it won't put you near the Cutter for the next part of the mission.",
        "After the cutscene from zoning into Arrapago Reef , approach the Cutter to receive another cutscene that finishes this mission. If you entered from Caedarva Mire at (G-9), you are already at the correct entrance. Just walk north to find the boat. L70 Shades are near the boat area.",
        "DO NOT WARP OUT -- The next mission is easily accessible on foot from here. Head south from the Cutter and into Caedarva Mire .",
        "Best route as of the August 2025 Version Update: Purchase an Arrapago Ring with 100 Imperial standing accolades from Asrahd at Aht Urhgan Whitegate (I-8). This will put you very close to the next step of the mission as well.",
        "Option 1, use the Survival Guide in Caedarva Mire and head North / Northwest before turning South to the Arrapago Reef (4) entrance.",
        "Option 2, use Dvucca Isle Staging Point and use the Caedarva Mire map #2 to zone into the Arrapago Reef (3) off-map/hidden G-9 entrance.",
        "Option 3, use the Ilrusi Atoll Staging Point to receive the initial cutscene, but may be further from the Cutter for the remaining mission requirements.",
        "Option 4, go to the Survival Guide in Arrapago Reef directly for the cutscene, but it won't put you near the Cutter for the next part of the mission.",
        "If you entered from Caedarva Mire at (G-9), you are already at the correct entrance. Just walk north to find the boat. L70 Shades are near the boat area.",
      }
    },
    {
      id = "mission_toau_31",
      name = "Aht Urhgan Mission 31",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 31,
      game_id = 0,
      repeatable = false,
      steps = {
        "Head to Dvucca Isle Staging Point in Caedarva Mire . If you go south from the Cutter and zone into Caedarva Mire you will be very close to the staging point.",
        "Enter Periqia via the Runic Seal just West from where you arrive at Dvucca Isle Staging Point . If you do not have Dvucca Isle Staging Point <-- click the link for how to unlock it.",
        "This fight is against up to 10x K23H1-LAMIA . After enough are defeated, a random amount, the battle ends. Trusts may be summoned. All the K23H1-LAMIA are located together at (H-9). They all have true sight and link. All of the K23H1-LAMIA attacks have the added effect of Poison . They can also use the WS Venomous Tail which has a very strong Poison effect (at least 80 HP a tick).",
        "Upon winning this battle, you'll receive a cutscene that finish this mission. If you fail the battle, you can obtain another permit to enter from Nahshib after one game day.",
        "If you go south from the Cutter and zone into Caedarva Mire you will be very close to the staging point.",
        "If you do not have Dvucca Isle Staging Point <-- click the link for how to unlock it.",
        "Trusts may be summoned.",
        "All the K23H1-LAMIA are located together at (H-9).",
        "They all have true sight and link.",
        "All of the K23H1-LAMIA attacks have the added effect of Poison .",
        "They can also use the WS Venomous Tail which has a very strong Poison effect (at least 80 HP a tick).",
        "If you fail the battle, you can obtain another permit to enter from Nahshib after one game day.",
        "If you have already finished this mission, you do not need another permit to help others with it.",
      }
    },
    {
      id = "mission_toau_32",
      name = "Aht Urhgan Mission 32",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 32,
      game_id = 0,
      repeatable = false,
      steps = {
        "Speak to Naja Salaheem .",
      }
    },
    {
      id = "mission_toau_33",
      name = "Aht Urhgan Mission 33",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 33,
      game_id = 0,
      repeatable = false,
      steps = {
        "Wait a game day and zone before speaking to Naja Salaheem again. While waiting you can get the Ephramadian gold coin needed for the next mission. Take the West exit out of Nashmau to Caedarva Mire or use the Home Point that you should have picked up a few missions earlier and head Southeast. Click on Jazaratt's Headstone at (E-10) for another Ephramadian gold coin .",
        "While waiting you can get the Ephramadian gold coin needed for the next mission.",
        "Take the West exit out of Nashmau to Caedarva Mire or use the Home Point that you should have picked up a few missions earlier and head Southeast. Click on Jazaratt's Headstone at (E-10) for another Ephramadian gold coin .",
      }
    },
    {
      id = "mission_toau_34",
      name = "Aht Urhgan Mission 34",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 34,
      game_id = 0,
      repeatable = false,
      steps = {
        "You will need another Ephramadian gold coin for this mission. Check Jazaraat's Headstone at (E-10) in Caedarva Mire for another coin. (This can be easily reached from Caedarva Mire HP#1 or the western exit of Nashmau )",
        "Travel to the Cutter . To access the Cutter, first travel to Dvucca Isle Staging Point and exit into the Mire. Alternatively, use the Survival Guide in Caedarva Mire and head south to the Arrapago Reef zone. This is not the zone directly behind you into Arrapago Reef . Leave the tunnel into an open area with Qutrub and Lamia and head south. Alternatively, purchase and use an Arrapago Ring with 100 Imperial standing accolades from Asrahd at Aht Urhgan Whitegate (I-8). This places you a few yalms from the Cutter . Head West to (G-9) and zone into Arrapago Reef . Head North to (H-8) to find the Cutter.",
        "You will end up in Talacca Cove once the cutscene ends. Don't warp away, the next mission is on Talacca Cove",
        "Check Jazaraat's Headstone at (E-10) in Caedarva Mire for another coin. (This can be easily reached from Caedarva Mire HP#1 or the western exit of Nashmau )",
        "To access the Cutter, first travel to Dvucca Isle Staging Point and exit into the Mire. Alternatively, use the Survival Guide in Caedarva Mire and head south to the Arrapago Reef zone. This is not the zone directly behind you into Arrapago Reef . Leave the tunnel into an open area with Qutrub and Lamia and head south. Alternatively, purchase and use an Arrapago Ring with 100 Imperial standing accolades from Asrahd at Aht Urhgan Whitegate (I-8). This places you a few yalms from the Cutter .",
        "Head West to (G-9) and zone into Arrapago Reef .",
        "Head North to (H-8) to find the Cutter.",
        "Alternatively, use the Survival Guide in Caedarva Mire and head south to the Arrapago Reef zone. This is not the zone directly behind you into Arrapago Reef . Leave the tunnel into an open area with Qutrub and Lamia and head south.",
        "Alternatively, purchase and use an Arrapago Ring with 100 Imperial standing accolades from Asrahd at Aht Urhgan Whitegate (I-8). This places you a few yalms from the Cutter .",
        "Don't warp away, the next mission is on Talacca Cove",
      }
    },
    {
      id = "mission_toau_35",
      name = "Aht Urhgan Mission 35",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 35,
      game_id = 0,
      repeatable = false,
      steps = {
        "Were you looking for ★Legacy of the Lost (HTMB) ?",
        "After the last mission you will end up in a CS in Talacca Cove . For others joining you, the closest teleport is Caedarva Mire HP#1",
        "Examine the Rock Slab directly in front of you to enter the BC.",
        "This is a 30 minute fight against Gessho . As a Ninja type monster, he can use Ninjutsu , Mijin Gakure , and ranged attacks. He has the ability to warp around the arena at will. He tends to follow this up with a TP move. Has access to the following TP moves: Hane Fubuki : Ranged attack that has the additional effect of Poison . Happobarai : AoE damage + Stun . Absorbed by shadows. Hiden Sokyaku : Knockback + Stun Rinpyotosha : Warcry Shiko no Mitate : Defense Boost Shibaraku : AoE damage and knockback. Absorbed by shadows. He will periodically spawn 3-6 clones of himself during battle. Each clone is relatively weak and only has around 2,000 HP . The clones will despawn within about 20 seconds of being summoned, but they do not always dissapear at the same time as each other. The clones can all use Ninjutsu and Ninja abilities including Mijin Gakure . The clones can Mijin Gakure together with Gessho , causing massive damage. The clones appear to be immune to all forms of Sleep . Gessho will give up at about 15% HP .",
        "Upon winning this battle, you'll receive the final cutscene .",
        "For others joining you, the closest teleport is Caedarva Mire HP#1",
        "As a Ninja type monster, he can use Ninjutsu , Mijin Gakure , and ranged attacks.",
        "He has the ability to warp around the arena at will. He tends to follow this up with a TP move.",
        "Has access to the following TP moves: Hane Fubuki : Ranged attack that has the additional effect of Poison . Happobarai : AoE damage + Stun . Absorbed by shadows. Hiden Sokyaku : Knockback + Stun Rinpyotosha : Warcry Shiko no Mitate : Defense Boost Shibaraku : AoE damage and knockback. Absorbed by shadows.",
        "He will periodically spawn 3-6 clones of himself during battle. Each clone is relatively weak and only has around 2,000 HP . The clones will despawn within about 20 seconds of being summoned, but they do not always dissapear at the same time as each other. The clones can all use Ninjutsu and Ninja abilities including Mijin Gakure . The clones can Mijin Gakure together with Gessho , causing massive damage. The clones appear to be immune to all forms of Sleep .",
        "Gessho will give up at about 15% HP .",
        "He tends to follow this up with a TP move.",
        "Hane Fubuki : Ranged attack that has the additional effect of Poison .",
        "Happobarai : AoE damage + Stun . Absorbed by shadows.",
        "Hiden Sokyaku : Knockback + Stun",
        "Rinpyotosha : Warcry",
        "Shiko no Mitate : Defense Boost",
        "Shibaraku : AoE damage and knockback. Absorbed by shadows.",
        "Each clone is relatively weak and only has around 2,000 HP .",
        "The clones will despawn within about 20 seconds of being summoned, but they do not always dissapear at the same time as each other.",
        "The clones can all use Ninjutsu and Ninja abilities including Mijin Gakure . The clones can Mijin Gakure together with Gessho , causing massive damage.",
        "The clones appear to be immune to all forms of Sleep .",
        "The clones can Mijin Gakure together with Gessho , causing massive damage.",
      }
    },
    {
      id = "mission_toau_36",
      name = "Aht Urhgan Mission 36",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 36,
      game_id = 0,
      repeatable = false,
      steps = {
        "Zone into Hazhalm Testing Grounds ( Caedarva Mire Map#1 D-9) for a cutscene . The last mission puts you close if you go left then take the first tunnel. The Caedarva Mire Homepoint #1 is the closest warp to Hazhalm Testing Grounds . Alternatively you can warp to Nashmau via HP and take the Western exit to get to Hazhalm Testing Grounds .",
        "Check the Entry Gate for the final cutscene .",
        "The last mission puts you close if you go left then take the first tunnel.",
        "The Caedarva Mire Homepoint #1 is the closest warp to Hazhalm Testing Grounds .",
        "Alternatively you can warp to Nashmau via HP and take the Western exit to get to Hazhalm Testing Grounds .",
      }
    },
    {
      id = "mission_toau_37",
      name = "Aht Urhgan Mission 37",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 37,
      game_id = 0,
      repeatable = false,
      steps = {
        "Enter Salaheem's Sentinels for a cutscene.",
      }
    },
    {
      id = "mission_toau_38",
      name = "Aht Urhgan Mission 38",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 38,
      game_id = 0,
      repeatable = false,
      steps = {
        "Wait until the end of the current game day and zone before heading to the Shararat Teahouse for a cutscene.",
      }
    },
    {
      id = "mission_toau_39",
      name = "Aht Urhgan Mission 39",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 39,
      game_id = 0,
      repeatable = false,
      steps = {
        "Head to Ru'Lude Gardens and approach the palace doors for a cutscene. Multiple cutscenes are given here so make sure this one involves you directly speaking with Trion .",
        "Multiple cutscenes are given here so make sure this one involves you directly speaking with Trion .",
      }
    },
    {
      id = "mission_toau_40",
      name = "Aht Urhgan Mission 40",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 40,
      game_id = 0,
      repeatable = false,
      steps = {
        "(Optional) Speak to Pherimociel in Ru'Lude Gardens (G-6) for a brief cutscene.",
        "Wait until next game day and zone after completing the previous mission before speaking to Pherimociel again for the next cutscene.",
        "When the cutscene is over, you will end up at the Leypoint in Wajaom Woodlands .",
      }
    },
    {
      id = "mission_toau_41",
      name = "Aht Urhgan Mission 41",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 41,
      game_id = 0,
      repeatable = false,
      steps = {
        "Speak to Rodin-Comidin outside the Automaton Workshop in Aht Urhgan Whitegate (I-7).",
        "Head to Nyzul Isle Staging Point and prepare for a battle.",
      }
    },
    {
      id = "mission_toau_42",
      name = "Aht Urhgan Mission 42",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 42,
      game_id = 0,
      repeatable = false,
      steps = {
        "Activate the blank target (J-9) at the Nyzul Isle Staging Point which is right next to the Runic Portal (the deactivated lamp) and select \"Yes\" to proceed with the mission.",
        "Check the Runic Seal (I-9), straight ahead, to enter the battlefield Path of Darkness . Trusts can be called during the battle.",
        "Naja Salaheem will fight with you during this battle. She must be kept alive, or the mission will end in failure. Recommend quick AoE action to pull hate on all the gears, they can kill Naja quickly, even at iLvl. Suggestion is to not run in and engage quickly, just aggro Amnaf . Let the gears spawn and then gather them all on you. With the adjustment to Trust Valaineral's Uriel Blade, he can quickly gain hate on the gears if you are on a job without AOE.",
        "The BC consists of three fights. If you fail, return to Rodin-Comidin in in Aht Urghan Whitegate for another key item to try again.",
        "Trusts can be called during the battle.",
        "She must be kept alive, or the mission will end in failure.",
        "Recommend quick AoE action to pull hate on all the gears, they can kill Naja quickly, even at iLvl.",
        "Suggestion is to not run in and engage quickly, just aggro Amnaf . Let the gears spawn and then gather them all on you.",
        "With the adjustment to Trust Valaineral's Uriel Blade, he can quickly gain hate on the gears if you are on a job without AOE.",
        "If you fail, return to Rodin-Comidin in in Aht Urghan Whitegate for another key item to try again.",
        "The first fight is against Amnaf and 4x Imperial Gears . The gears will not spawn until Amnaf is aggro'd. The gears can be slept , but not very easily. They are however, susceptible to both Gravity and Bind . (Note: Unsurprisingly, this is very easy to do at ilvl at all steps.) Amnaf can be slept . Naja will pick one of the enemies at random to fight.",
        "Once defeated, Amnaf will warp one room over.",
        "Naja will wait for a bit before heading into the next room.",
        "The gears will not spawn until Amnaf is aggro'd.",
        "The gears can be slept , but not very easily. They are however, susceptible to both Gravity and Bind . (Note: Unsurprisingly, this is very easy to do at ilvl at all steps.)",
        "Amnaf can be slept .",
        "Naja will pick one of the enemies at random to fight.",
        "The second fight is once again against Amnaf and 4x Imperial Gears (Triple Gears). The gears are much easier to sleep this time.",
        "Naja will pick one of the enemies at random to fight.",
        "Amnaf gives up and warps away at about 25% HP .",
        "The gears are much easier to sleep this time.",
        "This fight is against only Amnaf , but this time she turns into a Soulflayer . Her Sleepga resets hate on all players who are hit by it.",
        "Defeat Amnaf to finish the BC.",
        "Her Sleepga resets hate on all players who are hit by it.",
        "Upon winning this Battlefield, you'll receive one last cutscene that completes this mission.",
      }
    },
    {
      id = "mission_toau_43",
      name = "Aht Urhgan Mission 43",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 43,
      game_id = 0,
      repeatable = false,
      steps = {
        "Approach Naja Salaheem back in Aht Urhgan Whitegate for a cutscene.",
      }
    },
    {
      id = "mission_toau_44",
      name = "Aht Urhgan Mission 44",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 44,
      game_id = 0,
      repeatable = false,
      steps = {
        "Check the blank target at the Nyzul Isle Staging Point for a cutscene.",
        "Head to the Runic Seal (I-9) to enter the battlefield.",
        "The time limit for this fight is 45 minutes. This fight was initially capped at level 75. Level 99 players should have little to no difficulty with it. Trusts can be summoned in this fight.",
        "This fight is broken into three separate battles.",
        "This fight was initially capped at level 75. Level 99 players should have little to no difficulty with it.",
        "Trusts can be summoned in this fight.",
        "Raubahn re-raises twice during this fight, meaning you must defeat him three times to move on.",
        "He has access to all Blue Mage spells and abilities.",
        "Each time he re-raises , his job abilities, including his Azure Lore timer are reset.",
        "He seems to favor the spell Eyes On Me and will cast it often. The damage from this spell goes up considerably when parred with Azure Lore , doing well over 1,000 damage.",
        "Every time he uses Azure Lore he will follow it up with Eyes On Me .",
        "He has access to sword Weapon Skills . Mages should be especially careful of his Circle Blade .",
        "The final time he re-raises , he will have an immunity to either melee, magic, or ranged damage. The immunity is determined by what form of damage you used to deal the most damage to him. If you used mostly melee damage for the first 2 rounds, he will be immune to melee in the third round, ect. If you mix the type of damage you deal, i.e. magic round one and melee round 2, he will have no immunity the third round, but he will have increased defense.",
        "The damage from this spell goes up considerably when parred with Azure Lore , doing well over 1,000 damage.",
        "Mages should be especially careful of his Circle Blade .",
        "The immunity is determined by what form of damage you used to deal the most damage to him. If you used mostly melee damage for the first 2 rounds, he will be immune to melee in the third round, ect.",
        "If you mix the type of damage you deal, i.e. magic round one and melee round 2, he will have no immunity the third round, but he will have increased defense.",
        "He is unable to move at all during the fight.",
        "He is a Paladin type monster and has access to Banish IV, Banishga III, Dia III , and Holy II.",
        "At 50% HP he uses Perfect Defense and becomes immune to all forms of damage for a short time.",
        "This part of the battle is likely to take the longest to finish so plan accordingly.",
        "Like Razfahd he cannot move at all during the fight.",
        "He is a Paladin type monster and has access to Banish IV, Banishga III, Dia III , and Holy II and Mega Holy.",
        "He has access to the following abilities: Draw In: Used only when the person with hate moves too far away. Radiant Sacrament: AoE and wipes Utsusemi . Additional Effect: Magic Defense Down . Void of Repentance: Terrorizes target. Gospel of the Lost: Heals for around 900-1100 HP and removes debuffs. This move can be stunned , but it has a very quick casting time. Divine Spear: Damage + additional effect of attack -25%. Divine Judgement: AoE 1000+ damage and clears Utsusemi . He will use this ability at 50% of his HP and several times again as his health decreases. He will say \"ΩΩΩΩΩΩΩ\" just before using this move. Perfect Defense : He becomes immune to all forms of damage for a short time.",
        "The battle is over once Alexander is defeated.",
        "Draw In: Used only when the person with hate moves too far away.",
        "Radiant Sacrament: AoE and wipes Utsusemi . Additional Effect: Magic Defense Down .",
        "Void of Repentance: Terrorizes target.",
        "Gospel of the Lost: Heals for around 900-1100 HP and removes debuffs. This move can be stunned , but it has a very quick casting time.",
        "Divine Spear: Damage + additional effect of attack -25%.",
        "Divine Judgement: AoE 1000+ damage and clears Utsusemi . He will use this ability at 50% of his HP and several times again as his health decreases. He will say \"ΩΩΩΩΩΩΩ\" just before using this move.",
        "Perfect Defense : He becomes immune to all forms of damage for a short time.",
        "This move can be stunned , but it has a very quick casting time.",
        "If you fail this fight, return to Naja Salaheem for another key item to try again.",
        "If you win this fight, you'll watch one last cutscene that finishes this mission.",
      }
    },
    {
      id = "mission_toau_45",
      name = "Aht Urhgan Mission 45",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 45,
      game_id = 0,
      repeatable = false,
      steps = {
        "Approach Naja Salaheem for a cutscene.",
      }
    },
    {
      id = "mission_toau_46",
      name = "Aht Urhgan Mission 46",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 46,
      game_id = 0,
      repeatable = false,
      steps = {
        "Before you can continue, Naja Salaheem will ask that you wear something more appropriate to the palace.",
        "Wearing the following armors are known to allow you to continue: Adaman Cuirass Aketon Amir Korazin Arhat's Gi Barone Corazza Black Cloak Black Cotehardie Blessed Bliaut Blue Cotehardie Byrnie Brigandine Can be obtained for free via RoE - Conflict: Beadeaux Cardinal Vest Chasuble Dusk Jerkin Dragon Harness Errant Houppelande Hachiman Domaru Haubergeon Hauberk Holy Breastplate Homam Corazza Igqira Weskit Jaridah Peti Justaucorps Nashira Manteel Noble's Tunic Pahluwan Khazagand Plastron Rasetsu Samue Scorpion Harness Sipahi Jawshan Sha'ir Manteel Vermillion Cloak Yigit Gomlek",
        "In addition to the listed armor, you must also be wearing gloves, leg armor, and boots. However, they do not have to match anything else you are wearing.",
        "Check the Imperial Whitegate door at (L-8) in Aht Urhgan Whitegate with the proper attire and your weapons (and shield) removed for a cutscene.",
        "Adaman Cuirass",
        "Aketon",
        "Amir Korazin",
        "Arhat's Gi",
        "Barone Corazza",
        "Black Cloak",
        "Black Cotehardie",
        "Blessed Bliaut",
        "Blue Cotehardie",
        "Byrnie",
        "Brigandine Can be obtained for free via RoE - Conflict: Beadeaux",
        "Cardinal Vest",
        "Chasuble",
        "Dusk Jerkin",
        "Dragon Harness",
        "Errant Houppelande",
        "Hachiman Domaru",
        "Haubergeon",
        "Hauberk",
        "Holy Breastplate",
        "Homam Corazza",
        "Igqira Weskit",
        "Jaridah Peti",
        "Justaucorps",
        "Nashira Manteel",
        "Noble's Tunic",
        "Pahluwan Khazagand",
        "Plastron",
        "Rasetsu Samue",
        "Scorpion Harness",
        "Sipahi Jawshan",
        "Sha'ir Manteel",
        "Vermillion Cloak",
        "Yigit Gomlek",
        "Can be obtained for free via RoE - Conflict: Beadeaux",
      }
    },
    {
      id = "mission_toau_47",
      name = "Aht Urhgan Mission 47",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 47,
      game_id = 0,
      repeatable = false,
      steps = {
        "One of the following:",
        "You get to choose your ring now! You don't have to pick now, but you will still get the Imperial Standard . You may now change your Aht Urhgan Mission reward by disposing of your previous ring and speaking to Nadeey in Aht Urhgan Whitegate (J-7). If you dispose of a ring again, the timer to reacquire another reward will reset with the next conquest tally. (Sunday 0:00 JST)",
        "You don't have to pick now, but you will still get the Imperial Standard .",
        "You may now change your Aht Urhgan Mission reward by disposing of your previous ring and speaking to Nadeey in Aht Urhgan Whitegate (J-7). If you dispose of a ring again, the timer to reacquire another reward will reset with the next conquest tally. (Sunday 0:00 JST)",
      }
    },
    {
      id = "mission_toau_48",
      name = "Aht Urhgan Mission 48",
      type = "mission",
      location = "aht_urhgan",
      nation = "aht_urhgan",
      mission_index = 48,
      game_id = 0,
      repeatable = false,
      steps = {
        "Approach Naja Salaheem for the final cutscene and to get your Glory Crown back.",
        "After completing this mission, you may obtain Nashmeira as a trust by returning to the Imperial Whitegate.",
      }
    },
}

return missions
