-- Missions
-- Auto-generated from bg-wiki

local missions = {
  {
    id = "mission_windurst_1_1",
    name = "Mission 1-1",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 1,
    game_id = 0,
    repeatable = false,
    steps = {
      "Accept mission from any Gate Guard.",
      "Speak to Hakkuru-Rinkuru at Port Windurst (E-7) for cutscene.",
      "Go to East Sarutabaruta (J-7) and enter Inner Horutoto Ruins.",
      "Go downstairs to the main room of Lily Tower.",
      "Pass through Cracked Wall at (H-9), then go left.",
      "Examine Gate: Magical Gizmo at (I-9) for cutscene.",
      "Check each Ancient Magical Gizmo until you receive Cracked Mana Orb.",
      "Return to Hakkuru-Rinkuru in Port Windurst to complete mission.",
    }
  },
  {
    id = "mission_windurst_1_2",
    name = "Mission 1-2",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 2,
    game_id = 0,
    repeatable = false,
    steps = {
      "Accept mission from any Gate Guard.",
      "Speak to Apururu at Windurst Woods (H-9) in the Manustery.",
      "Receive six dark Mana Orb key items.",
      "Go to East Sarutabaruta (J-11) and speak to Pore-Ohre to receive Southeastern star charm.",
      "Enter Marguerite Tower to reach Outer Horutoto Ruins.",
      "Place Mana Orbs on all six pedestals (check Cracked Walls for hidden rooms).",
      "Pass through Cracked Wall on east side and examine Gate: Magical Gizmo for cutscene.",
      "Retrieve all six Glowing Mana Orbs from the pedestals.",
      "Exit the tower to East Sarutabaruta for cutscene.",
      "Return to Apururu to complete mission.",
    }
  },
  {
    id = "mission_windurst_1_3",
    name = "Mission 1-3",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 3,
    game_id = 0,
    repeatable = false,
    steps = {
      "Accept mission from any Gate Guard.",
      "Speak to Leepe-Hoppe at Windurst Waters (J-9) on the Rhinostery roof.",
      "Receive Food offering and Drink offering.",
      "Go to Giddeus at West Sarutabaruta (F-8).",
      "Speak to Laa Mozi at Giddeus (H-7) and give Food offering.",
      "Speak to Ghoo Pakya at Giddeus (G-7) and give Drink offering.",
      "Return to the Rhinostery and climb stairs for cutscene.",
      "Return to any Gate Guard to complete mission.",
    }
  },
  {
    id = "mission_windurst_2_1",
    name = "Mission 2-1",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 4,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Speak to Tosuka-Porika at Windurst Waters (G-8) in the Optistery.",
      "Speak to Nanaa Mihgo at Windurst Woods (J-3) to receive Lapis monocle.",
      "Go to Maze of Shakhrami at Tahrongi Canyon (K-5).",
      "On Map 1, go to (G-6) to transition to Map 2.",
      "On Map 2, check Fossil Rocks at (H-5), (I-7), (H-7), (G-7), (G-8), (I-8) until you receive Lapis coral.",
      "Return to Nanaa Mihgo to receive Hideout key.",
      "Go to East Sarutabaruta (J-7) and enter Inner Horutoto Ruins via Lily Tower.",
      "Go to southwest room, pass through Cracked Wall at (G-9) to reach Map 2.",
      "Navigate to (G-8) and examine Mahogany Door for cutscene.",
      "Go to House of the Hero at Windurst Walls (G-3) and check door for cutscene.",
      "Return to Tosuka-Porika to complete mission.",
    }
  },
  {
    id = "mission_windurst_2_2",
    name = "Mission 2-2",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 5,
    game_id = 0,
    repeatable = false,
    steps = {
      "Accept mission from Gate Guard.",
      "Speak to Moreno-Toeno at Windurst Waters (L-6) in the Aurastery to receive Creature Counter.",
      "Go to Tahrongi Canyon and defeat 30 monsters within 1 Earth hour.",
      "Return to Moreno-Toeno after defeating 30 monsters.",
      "Go to Buburimu Peninsula and defeat 30 monsters within 2 Earth hours.",
      "Return to Moreno-Toeno after defeating 30 monsters.",
      "Speak to Moreno-Toeno in the final game hour of the time limit to complete mission.",
    }
  },
  {
    id = "mission_windurst_2_3",
    name = "Mission 2-3",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 6,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Speak to Kupipi in Heavens Tower to receive Letter to the consuls.",
      "Choose either Bastok or San d'Oria path first.",
      "--- BASTOK PATH ---",
      "Speak to Patt-Pott at Bastok Metalworks (I-7) in Windurstian Consulate.",
      "Speak to Pius in President's Office (J-8).",
      "Speak to Grohm at Craftsmen's Eatery (H-9) to receive 3 Pickaxes.",
      "Go to Palborough Mines in North Gustaberg.",
      "Mine Mythril Seams with Pickaxe until you receive Mine Gravel.",
      "On second floor, trade Mine Gravel to refiner at (I-7) and pull lever.",
      "Drop to level below and pull another lever to receive Mythril Sand.",
      "Trade Mythril Sand to Patt-Pott, then speak to him again.",
      "--- SAN D'ORIA PATH ---",
      "Speak to Kasaroro at Northern San d'Oria (H-9) in Windurstian Consulate.",
      "Speak to Halver in Chateau d'Oraguille.",
      "Go to Horlais Peak via Ghelsba Outpost and Yughott Grotto (J-6).",
      "Enter BCNM 'The Rank 2 Final Mission' (Level 25 cap).",
      "Defeat Seeker (Ahriman) and Dread Dragon.",
      "Return to Kasaroro.",
      "--- COMPLETION ---",
      "Return to Kupipi in Heavens Tower to complete mission.",
    }
  },
  {
    id = "mission_windurst_3_1",
    name = "Mission 3-1",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 7,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Speak to Kupipi in Heavens Tower to receive Starway Stairway bauble.",
      "Check door on left to go upstairs.",
      "Speak to Rhy Epocan at top of tower for cutscene.",
      "Speak to Hakkuru-Rinkuru at Port Windurst (E-7) in Orastery.",
      "Go to Castle Oztroja (I-8) on first map.",
      "Find the two switches and pull one to fall through trap door for cutscene.",
      "Return to Rhy Epocan to complete mission.",
    }
  },
  {
    id = "mission_windurst_3_2",
    name = "Mission 3-2",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 8,
    game_id = 0,
    repeatable = false,
    steps = {
      "Accept mission from Gate Guard.",
      "Go to Heavens Tower and speak to Zubaba on second floor to receive Charm of light.",
      "Go to East Sarutabaruta (J-7) and enter Inner Horutoto Ruins.",
      "Pass through Three Mage Gate (requires 3 mages: WHM, BLM, RDM).",
      "Continue to small room at (G-7).",
      "Examine Gate of Light for cutscene.",
      "Return to Zubaba in Heavens Tower to complete mission.",
      "Trade Rolanberry to Kupipi to receive Portal charm.",
    }
  },
  {
    id = "mission_windurst_3_3",
    name = "Mission 3-3",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 9,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Enter Vestal Chamber at top of Heavens Tower for cutscene. Receive Letter to the ambassador.",
      "Speak to Pakh Jatalfih at Ru'Lude Gardens (I-9) in Windurstian Embassy.",
      "Go to Lower Delkfutt's Tower.",
      "--- IF YOU HAVE DELKFUTT KEY ---",
      "Enter Basement via Cermet Door at (E-8) Map 1.",
      "Click Cermet Door at (L-7) for cutscene.",
      "--- IF YOU NEED DELKFUTT KEY ---",
      "Climb tower to Floor 10 in Upper Delkfutt's Tower.",
      "Defeat Mimas (NM Gigas) at door (H-7).",
      "Defeat Porphyrion (NM Gigas) to obtain Delkfutt Key.",
      "Trade key to elevator at (H-8).",
      "Walk down staircase to Basement.",
      "Click Cermet Door at (L-7) for cutscene.",
      "--- COMPLETION ---",
      "Return to Windurstian Embassy in Ru'Lude Gardens.",
      "Click Door: Windurstian Emb. (3rd door inside) to complete mission.",
    }
  },
  {
    id = "mission_windurst_4_1",
    name = "Mission 4-1",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 10,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar.",
      "Speak to Pakh Jatalfih at Ru'Lude Gardens (I-9) in Windurstian Embassy.",
      "Speak to ambassador in back chamber to receive Archducal audience permit.",
      "Click Audience Chamber door at Ru'Lude Gardens (H-6) for cutscene. Receive Letter to Aldo.",
      "Speak to Aldo in Lower Jeuno at Neptune's Spire Tenshodo H.Q. Receive Silver bell.",
      "--- PREREQUISITE KEY ITEMS ---",
      "Speak to Paya-Sabya at Upper Jeuno (I-8), then Muckvix at Lower Jeuno (H-9) for Yagudo torch.",
      "Speak to Sattal-Mansal at Lower Jeuno (J-8).",
      "Trade Quadav Charm separately for Coruscant rosary.",
      "Trade Quadav Augury Shell separately for Black matinee necklace.",
      "Speak to Baudin at Upper Jeuno (G-8), trade Coeurl Meat for Crest of Davoi.",
      "--- BEADEAUX MAGICITE ---",
      "Enter Beadeaux from Pashhow Marshlands (L-11).",
      "Use Mute device at (H-7) to silence yourself before passing Afflictors.",
      "Defeat De'Vyu Headhunter at (H-9/10) for Quadav Charm.",
      "Defeat Go'Bhu Gascon at (F-6) for Quadav Augury Shell.",
      "Trade both items separately to Sattal-Mansal.",
      "Enter Qulun Dome and examine Magicite for Magicite: Aurastone.",
      "--- DAVOI MAGICITE ---",
      "Enter Davoi in Jugner Forest (G-12).",
      "Go to (G-7), click Wall of Dark Arts to enter Monastic Cavern.",
      "Examine Magicite for Magicite: Optistone.",
      "--- CASTLE OZTROJA MAGICITE ---",
      "Enter Castle Oztroja in Meriphataud Mountains (L-8).",
      "Pass Brass Door at (I-8) using lever.",
      "Navigate to Map 7, light Torch at door (H-9).",
      "Enter Altar Room and examine Magicite for Magicite: Orastone.",
      "--- COMPLETION ---",
      "Click Audience Chamber at Ru'Lude Gardens (H-5) for cutscene.",
      "Speak to Pakh Jatalfih in Windurstian Embassy to complete mission.",
    }
  },
  {
    id = "mission_windurst_5_1",
    name = "Mission 5-1",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 11,
    game_id = 0,
    repeatable = false,
    steps = {
      "Click Door: Vestal Chamber at top of Heavens Tower to receive New Fei'Yin seal.",
      "Go to Fei'Yin in Beaucedine Glacier for cutscene with Zeid.",
      "Go to (K-8), open Cermet Portal to enter Qu'Bia Arena.",
      "Enter BCNM 'The Rank 5 Mission'.",
      "Defeat Archlich Taber'quoan (ignore lesser skeletons). Receive Burnt seal.",
      "Return to Heavens Tower.",
      "Check Door: Vestal Chamber to complete mission.",
    }
  },
  {
    id = "mission_windurst_5_2",
    name = "Mission 5-2",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 12,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Receive Star crested summons.",
      "Click Door: Vestal Chamber at top of Heavens Tower.",
      "Go to Castle Zvahl Keep and navigate to Throne Room.",
      "--- NAVIGATION TO THRONE ROOM ---",
      "Enter Castle Zvahl Baileys at Xarcabard (D-7/8).",
      "Follow path to first intersection, turn right.",
      "Navigate through Castle Zvahl Baileys and Keep using teleporters.",
      "Zone into Throne Room.",
      "--- BCNM ---",
      "Enter BCNM 'The Shadow Lord Battle'.",
      "Defeat Shadow Lord Phase 1 (alternates physical/magical immunity).",
      "Defeat Shadow Lord Phase 2 (AoE attacks only). Receive Shadow fragment.",
      "--- COMPLETION ---",
      "Zone into Heavens Tower for cutscene.",
      "Click Door: Vestal Chamber for final cutscene.",
    }
  },
  {
    id = "mission_windurst_6_1",
    name = "Mission 6-1",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 13,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Speak to Hakkuru-Rinkuru at Port Windurst (E-7) to receive Southwestern star charm.",
      "Go to West Sarutabaruta (F-11) and enter Outer Horutoto Ruins via Dahlia Tower.",
      "Pass through Cracked Wall at (I-8) on Map 4.",
      "Pass through second Cracked Wall at (J-8).",
      "Examine Gate: Magical Gizmo to spawn 4 Jack Cardians.",
      "Defeat the Cardians: Jack of Batons (BLM), Jack of Coins (RDM), Jack of Cups (WHM), Jack of Swords (PLD).",
      "Examine the door after defeating them for cutscene.",
      "Enter Full Moon Fountain in Toraimarai Canal for cutscene to complete mission.",
    }
  },
  {
    id = "mission_windurst_6_2",
    name = "Mission 6-2",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 14,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Click Door: Vestal Chamber at top of Heavens Tower. Receive Holy One's invitation.",
      "Go to Balga's Dais in Giddeus.",
      "Enter BCNM 'Saintly Invitation'.",
      "Defeat: Nuu Kofu the Gentle (WHM), Chaa Paqa the Profound (SMN), Buu Xolo the Bloodfaced (SAM), Juu Zeni the Poisonmist (NIN).",
      "Receive Balga champion certificate.",
      "Go to Castle Oztroja in Meriphataud Mountains.",
      "Navigate to Map 4.",
      "Defeat Yagudo Flagellants until you receive Judgment Key.",
      "Open large Brass Door by interacting with unlit Torch in corner rooms.",
      "Solve Brass Statue password to unlock trapdoor.",
      "After falling, go to smaller Brass Door at (H-5).",
      "Trade Judgment Key to Brass Door.",
      "Speak to Kaa Toru the Just for Holy One's oath and Ashura Necklace.",
      "Return to Door: Vestal Chamber in Heavens Tower to complete mission.",
    }
  },
  {
    id = "mission_windurst_7_1",
    name = "Mission 7-1",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 15,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Speak to Tosuka-Porika at Windurst Waters (G-8) to receive Optistery ring.",
      "Go to Toraimarai Canal (G-8) Map 2.",
      "Defeat the 4 Hinge Oils in the room.",
      "Examine Marble Door at (H-8) to enter The Animastery.",
      "Examine Tome of Magic on the ground for cutscene.",
      "Return to Tosuka-Porika to complete mission. Receive Blank Book of the Gods.",
    }
  },
  {
    id = "mission_windurst_7_2",
    name = "Mission 7-2",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 16,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Speak to Leepe-Hoppe at Windurst Waters (J-9) on Rhinostery roof.",
      "Speak to Kerutoto in Rhinostery northern building for cutscene.",
      "Speak to Romaa Mihgo at Kazham (H-11) in Mihgo's Residence.",
      "Go to Temple of Uggalepih.",
      "Defeat Bonze Marberry at Map 3 (J-9) to obtain Cursed Key.",
      "Trade Cursed Key to Granite Door at (J-6) for cutscene. Receive Book of the Gods.",
      "Return to Leepe-Hoppe to complete mission.",
    }
  },
  {
    id = "mission_windurst_8_1",
    name = "Mission 8-1",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 17,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Speak to Moreno-Toeno at Windurst Waters (L-6) to receive 'Star Seeker'.",
      "Examine Qu'Hau Spring at Ro'Maeve (H-6) for cutscene.",
      "Go to Davoi and enter Monastic Cavern from entrance 2 at (H-11).",
      "Exit at (I-8) and follow road west to wooden elevator.",
      "Defeat Dirtyhanded Gochakzuk (NM) inside monastery to obtain Curse Wand.",
      "Speak to Sedal-Godjal at Davoi (J-8) to convert 'Star Seeker' to Magic-drained 'Star Seeker'.",
      "Trade Curse Wand to Sedal-Godjal for cutscene.",
      "Return to Moreno-Toeno to complete mission.",
    }
  },
  {
    id = "mission_windurst_8_2",
    name = "Mission 8-2",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 18,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Speak to Apururu at Windurst Woods (H-9) to receive Manustery ring.",
      "--- COLLECT 3 RINGS ---",
      "Go to Fei'Yin (F-6) Map 2, click Cermet Door for cutscene with Rukususu. Receive Rhinostery ring.",
      "Go to Davoi (J-8) via Monastic Cavern, speak to Sedal-Godjal. Receive Aurastery ring.",
      "Speak to Tosuka-Porika at Windurst Waters (G-8). Receive Optistery ring.",
      "Return to Apururu for dialogue.",
      "--- GET ORASTERY RING ---",
      "Speak to Kupipi in Heavens Tower for cutscene.",
      "Go to West Sarutabaruta (F-4) and enter Outer Horutoto Ruins.",
      "Pass through Cracked Wall at (I-6).",
      "Touch Cracked Wall at (G-8) to spawn Queen of Coins (RDM) and Queen of Swords (PLD).",
      "Defeat them and click Cracked Wall again for cutscene. Receive Orastery ring.",
      "Return to Apururu for cutscene.",
      "--- GLOVE ---",
      "Speak to Shantotto at Windurst Walls (K-7) to receive Glove of perpetual twilight.",
      "Return to Apururu for cutscene.",
      "Go to Inner Horutoto Ruins and examine Gate of Darkness at (I-7) Map 4 for cutscene.",
      "Return to Apururu to complete mission.",
    }
  },
  {
    id = "mission_windurst_9_1",
    name = "Mission 9-1",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 19,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Speak to Apururu at Windurst Woods (H-9) for cutscene.",
      "Zone into Heavens Tower for cutscene.",
      "Click Door: Vestal Chamber at top floor for cutscene.",
      "Return to Apururu for cutscene.",
      "Obtain Goobbue Humus from Goobbue Gardeners in The Sanctuary of Zi'Tah.",
      "Trade Goobbue Humus to single Mandragora Warden at The Boyahda Tree (F-4) Map 1 hidden area.",
      "Receive Letter from Zonpa-Zippa.",
      "Return to Apururu for cutscene.",
      "Zone into Full Moon Fountain in Toraimarai Canal to complete mission.",
    }
  },
  {
    id = "mission_windurst_9_2",
    name = "Mission 9-2",
    type = "mission",
    location = "windurst",
    nation = "windurst",
    mission_index = 20,
    game_id = 0,
    repeatable = false,
    steps = {
      "Trade crystals to Conquest NPC to fill Rank bar, then accept mission from Gate Guard.",
      "Click Door: Vestal Chamber at top floor of Heavens Tower for cutscene.",
      "--- COLLECT 3 ANCIENT VERSES ---",
      "Examine Qu'Hua Spring at Ro'Maeve (H-6) for Ancient Verse of Ro'Maeve.",
      "Zone into Chamber of Oracles via Quicksand Caves for Ancient Verse of Altepa.",
      "Examine ??? at Temple of Uggalepih (E-8) Map 2 for Ancient Verse of Uggalepih.",
      "(Requires Uggalepih Key from Tonberry Cutters to open Granite Door)",
      "--- BCNM ---",
      "Return to Door: Vestal Chamber in Heavens Tower for cutscene.",
      "Go to Full Moon Fountain in Toraimarai Canal.",
      "Enter two-part BCNM.",
      "Part 1: Defeat Ace Cardians - Ace of Batons (BLM), Ace of Swords (PLD), Ace of Coins (RDM), Ace of Cups (WHM).",
      "Part 2: Defeat Wyvern and Manticore. Keep Ajido-Marujido alive.",
      "--- COMPLETION ---",
      "Return to Door: Vestal Chamber in Heavens Tower for cutscene.",
      "Click Door: Vestal Chamber again for final cutscene. Achieve Rank 10.",
    }
  },
}

return missions
