-- Missions
-- Auto-generated from bg-wiki

local missions = {
    {
      id = "mission_zilart_1",
      name = "Zilart Mission 1",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 1,
      game_id = 0,
      repeatable = false,
      steps = {
        "Entering Norg will trigger a cutscene. If you previously chose to postpone the cut-scene, use Tales' Beginning which is located near Home Point #1 in Norg to resume the story.",
        "If you previously chose to postpone the cut-scene, use Tales' Beginning which is located near Home Point #1 in Norg to resume the story.",
        "Norg is located on Elshimo Island , which can be reached one of the following ways: Kazham Airship Pass to travel from Port Jeuno to Kazham . If you are on or past Rhapsodies of Vanadiel Mission 1-5 , Pacomart and Tonasav can transport you to Norg .",
        "Additional methods become available once either of the above two conditions are met: Waypoints in Adoulin after purchasing the Norg warp rune or Kazham warp rune . Unity Warp after completion of 10 Records of Eminence objectives and joining a Unity . Sea Serpent Grotto in the CL 125 category is closest.",
        "NOTE: You must be minimum rank 6 in your home nation in order to continue any further from here.",
        "Kazham Airship Pass to travel from Port Jeuno to Kazham .",
        "If you are on or past Rhapsodies of Vanadiel Mission 1-5 , Pacomart and Tonasav can transport you to Norg .",
        "Waypoints in Adoulin after purchasing the Norg warp rune or Kazham warp rune .",
        "Unity Warp after completion of 10 Records of Eminence objectives and joining a Unity . Sea Serpent Grotto in the CL 125 category is closest.",
        "Sea Serpent Grotto in the CL 125 category is closest.",
      }
    },
    {
      id = "mission_zilart_2",
      name = "Zilart Mission 2",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 2,
      game_id = 0,
      repeatable = false,
      steps = {
        "Note: Depending on your timing you may see the cutscene with Iroha for a different Mission. If so, you'll want to re-enter the Oaken Door after that cutscene plays in order to get the cutscene for this Mission.",
        "Head for (L-8) in Norg and enter the Oaken Door . You'll receive a cutscene with Gilgamesh .",
      }
    },
    {
      id = "mission_zilart_3",
      name = "Zilart Mission 3",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 3,
      game_id = 0,
      repeatable = false,
      steps = {
        "Go to Kazham (J-9) and speak with Jakoh Wahcondalo . She will give you a Sacrificial Chamber key required to progress further in the Temple of Uggalepih . Using Elshimo Low > Kazham > Home Point #1 will bring you right next to the house of Jakoh Wahcondalo .",
        "Using Elshimo Low > Kazham > Home Point #1 will bring you right next to the house of Jakoh Wahcondalo .",
      }
    },
    {
      id = "mission_zilart_4",
      name = "Zilart Mission 4",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 4,
      game_id = 0,
      repeatable = false,
      steps = {
        "Note: Having a significant amount of Rancor can be very harmful as the mission requires you to combat several Tonberries , including Notorious Monsters that can use the ability Everyone's Rancor for a great amount of damage. The rancor can be lowered with the quest Everyone's Grudge located in Norg . Consider completing this before proceeding.",
        "One can avoid gaining rancor by calling for help as well.",
        "If you already have the Den of Rancor Home Point unlocked, you can use it to warp directly to the Den of Rancor, step into the Sacrificial Chamber, and enter the Battlefield for the boss fight.",
        "A player who has already completed this mission can use the home point and open the door for you, allowing you to skip the puzzle entirely. Use the Unity Warp (level 128) to reach the door if you are using this method.",
        "The overall goal of this mission is to reach the Sacrificial Chamber BCNM zone. Before that, your goal is to reach the Den of Rancor .",
        "Reaching the Den of Rancor",
        "Use the Den of Rancor Home Point #1 warp.",
        "The Unity warp to Den of Rancor (under content level 128) allows you to skip the Temple of Uggalepih step of Method #3 without the need for a Paintbrush of souls .",
        "This is the old fashioned way, by obtaining the Paintbrush of souls .",
        "You will also need one Unlit Lantern to access the Sacrificial Chamber area. Obtain one via the below methods, and continue on the Temple of Uggalepih steps.",
        "Temple of Uggalepih steps",
        "Enter the Temple from the main entrance in Yhoator Jungle (J-11/12). The Voidwatch warp brings you to this entrance.",
        "Make your way to the northwestern exit at (F-5). Pick up the Survival Guide on the way. You will zone out into Yhoator Jungle . Make a left after zoning.",
        "Enter the temple again from (H-11), and work your way down to the Temple Guardian at (I-10). Kill the guardian if he is up, otherwise the door will be open already.",
        "Go ahead to (I-7). The door is on the far side of the room. Whoever has the Paintbrush of souls needs to stand at the empty frame in the middle of the wall. Everyone else wait by the door. To use the Paintbrush, check the frame and confirm you wish to continue. You should get a message saying \"a new painting begins to appear on the canvas\". Wait 30 seconds without moving or entering any commands, and check it again. You should get another message about the Den of Rancor , and the door will open. The person who is checking the frame cannot be aggro'd or acted on during these 30 seconds, otherwise you'll have to start over.",
        "The Voidwatch warp brings you to this entrance.",
        "You will zone out into Yhoator Jungle . Make a left after zoning.",
        "Kill the guardian if he is up, otherwise the door will be open already.",
        "To use the Paintbrush, check the frame and confirm you wish to continue. You should get a message saying \"a new painting begins to appear on the canvas\". Wait 30 seconds without moving or entering any commands, and check it again. You should get another message about the Den of Rancor , and the door will open.",
        "The person who is checking the frame cannot be aggro'd or acted on during these 30 seconds, otherwise you'll have to start over.",
        "Den of Rancor steps",
        "Enter the Den of Rancor . Everyone will need Sneak and Invisible (Status) .",
        "Head to (E-5) on map 1. Once clear of the bomb mobs there, drop Invisible and trade your Unlit Lantern to the Altar of Rancor . You will receive a Rancor Flame item instead.",
        "Run to (F-7) and drop down the hole in the northeast corner to map 2. Make your way to (E-5) on this new map.",
        "To access the Sacrificial Chamber the four lanterns outside its gate need to be lit with Rancor Flame by trading the Unlit Lantern to an Altar of Rancor . While it can be done with one Unlit Lantern going back and forth from the Alter of Rancor and the lanterns, it would be suggested to farm multiple. 4 is ideal, but you can only hold one Lantern and one Flame at any time so that will require 4 players. Consider clearing the room, as it is hard to trade while being attacked.",
        "Consider clearing the room, as it is hard to trade while being attacked.",
        "After arriving at the Home Point in Den of Rancor",
        "Be sure to obtain the Home Point, and then walk further to zone into the Sacrificial Chamber .",
        "Examine the door to progress to the boss fight, see below for details. The name of the fight is the same as the mission, \"The Temple of Uggalepih\"",
        "The name of the fight is the same as the mission, \"The Temple of Uggalepih\"",
        "Inside, gather up and prepare. You will now enter an uncapped BCNM against 3 Tonberry NMs. Buff inside, as they'll wear upon entering the BC.",
        "Once you've cleared the BC, you'll get a cutscene. Afterwards, you'll exit on the other side of the Sacrificial Chamber , that will lead you back out to the Temple.",
        "After winning the BCNM, you may now continue Rhapsodies of Vanadiel Mission 2-24 The Cursed Temple .",
        "Grav'iton : Uses both Perfect Dodge and Everyone's Rancor.",
        "Molyb'iton : Uses Manafont at some point.",
        "Tungs'iton : Uses Astral Flow at some point, summoning an avatar to wreak havoc.",
        "Uses both Perfect Dodge and Everyone's Rancor.",
        "Uses Manafont at some point.",
        "Uses Astral Flow at some point, summoning an avatar to wreak havoc.",
        "Recommended to battle order of Grav'iton THF → Molyb'iton BLM → Tungs'iton SMN",
        "Grav'iton cannot be slept, and therefore should be defeated first. Silence and Sleep the other two.",
        "Grav'iton can use Everyone's Rancor, which does 10 times the damage of Everyone's Grudge . A tank can very easily be KOed by this if they have significant rancor.",
        "The Summoner will have a pet, but that does not indicate what avatar it will use for Astral Flow . Defeat it quickly to try and avoid Astral Flow. It probably won't KO you if it does use it, but it will cause you some issues. Make sure everyone has full HP before attacking it.",
      }
    },
    {
      id = "mission_zilart_5",
      name = "Zilart Mission 5",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 5,
      game_id = 0,
      repeatable = false,
      steps = {
        "After defeating the boss in the last mission, you can now continue Rhapsodies of Vanadiel Mission 2-24 The Cursed Temple .",
        "Due to the long nature of this mission, it is recommended that you take precautions to ensure that you have received the key items . This mission can take a while, as it requires travel to a lot of different places, some in the far corners of large and dangerous zones. Always ensure that when checking a headstone you receive the message that you obtained the key item .",
        "If you are too far away the game can give you the message, \"You need to move closer to key item \" and at a quick glance this can appear the same as you acquiring it. Be sure to double check.",
        "There are two types of headstones, one type only gives the key item , others spawn NMs that you must defeat before you may receive the key item .",
        "Several headstones are close to Cloister home points, it's recommended to grab those on the way if you haven't unlocked them yet.",
        "Dark Fragment:",
        "Obtained upon completion of The Temple of Uggalepih from Grav'iton.",
        "Earth Fragment:",
        "Proceed to (J-9) in Western Altepa Desert , and enter the Quicksand Caves (Map 3).",
        "Head to (K-6) and fall down the sandpit.",
        "Follow the pathway until you exit back out to Western Altepa Desert . Unity warp 125 Western Altepa Desert will land you within this area cutting out the need to go through Quicksand Caves . From the Unity Warp : Turn around and walk into the crevasse (this cannot be accessed from the outside but the Unity Warp puts you on top of the stone that you cannot normally walk onto.) Follow the path, turning right at the fork until you come to a plunger-looking statue (Ruby Column). Press it down if it is up to continue. Go through the open door near the end of this path and follow it until you exit out at the square shaped crevasse. Turn left and enter the first open door. When you exit again the headstone is located in this section.",
        "Move in a southwesterly direction towards (H-8)/(H-9) to locate the Cermet Headstone . Examine it to receive the Earth fragment .",
        "Unity warp 125 Western Altepa Desert will land you within this area cutting out the need to go through Quicksand Caves .",
        "From the Unity Warp : Turn around and walk into the crevasse (this cannot be accessed from the outside but the Unity Warp puts you on top of the stone that you cannot normally walk onto.) Follow the path, turning right at the fork until you come to a plunger-looking statue (Ruby Column). Press it down if it is up to continue. Go through the open door near the end of this path and follow it until you exit out at the square shaped crevasse. Turn left and enter the first open door. When you exit again the headstone is located in this section.",
        "Turn around and walk into the crevasse (this cannot be accessed from the outside but the Unity Warp puts you on top of the stone that you cannot normally walk onto.)",
        "Follow the path, turning right at the fork until you come to a plunger-looking statue (Ruby Column). Press it down if it is up to continue.",
        "Go through the open door near the end of this path and follow it until you exit out at the square shaped crevasse.",
        "Turn left and enter the first open door. When you exit again the headstone is located in this section.",
        "Water Fragment:",
        "Note: the Geomagnetic Fount for La Theine Plateau will let out in the same chasm as the Cermet Headstone .",
        "Proceed to La Theine Plateau and enter Ordelle's Caves around (F-7), alternatively you can use Survival Guide to get here. This places you on Map 2. Follow the path east to (I-6)(exit B) and you'll switch to Map 1. (East according to map, so left from where you enter.) Continue down the tunnel to (G-8). From there, go east and enter the south tunnel (exit D) around (H-9). Head up the stairs and south until you reach the hole that is at the southside of (H-11), at the transition between (H-11) and (H-12). Go east to another tunnel (E, Map 3), taking special care not to fall off the cliffs, and head up. Once you get to about (I-6), go south. Continue on until (H-9) and you'll see a tunnel going west, the zone is not far ahead, bringing you back out to La Theine Plateau . If you don't have the Geomagnetic-Fount, it will be on the right on a ledge after zoning to the Plateau. Get close to it and interact with it from below to register it. The Cermet Headstone is at the end of the valley at G-11. Examine it to receive the Water fragment .",
        "Follow the path east to (I-6)(exit B) and you'll switch to Map 1. (East according to map, so left from where you enter.)",
        "Continue down the tunnel to (G-8).",
        "From there, go east and enter the south tunnel (exit D) around (H-9).",
        "Head up the stairs and south until you reach the hole that is at the southside of (H-11), at the transition between (H-11) and (H-12).",
        "Go east to another tunnel (E, Map 3), taking special care not to fall off the cliffs, and head up.",
        "Once you get to about (I-6), go south.",
        "Continue on until (H-9) and you'll see a tunnel going west, the zone is not far ahead, bringing you back out to La Theine Plateau . If you don't have the Geomagnetic-Fount, it will be on the right on a ledge after zoning to the Plateau. Get close to it and interact with it from below to register it.",
        "The Cermet Headstone is at the end of the valley at G-11. Examine it to receive the Water fragment .",
        "If you don't have the Geomagnetic-Fount, it will be on the right on a ledge after zoning to the Plateau. Get close to it and interact with it from below to register it.",
        "Ice Fragment:",
        "Make your way to the Cloister of Frost in the basement of Fei'Yin . The Cermet Headstone is in the back of the room. Examine it to receive the Ice fragment . Fei'Yin Homepoint #2 is right outside the Cloister, if you already have it. A level 20+ Summoner can start Trial-Size Trial by Ice to be teleported to the Cloister. Don't forget to step outside and grab Fei'Yin Homepoint #2 for later use, especially if you are completing the Trial-Sized quest.",
        "Fei'Yin Homepoint #2 is right outside the Cloister, if you already have it.",
        "A level 20+ Summoner can start Trial-Size Trial by Ice to be teleported to the Cloister. Don't forget to step outside and grab Fei'Yin Homepoint #2 for later use, especially if you are completing the Trial-Sized quest.",
        "Fire Fragment:",
        "Note : The one way drops make starting from the Cloister of Flames or the Ifrit's Cauldron Homepoint (i.e. via Mini Fork of Fire ) a longer trip that ends up passing the entrance from Yhoator Jungle / Survival Guide on Map 4 anyway. All three travel options ( Teleport-Yhoat , the Yhoator Jungle Survival Guide, or the Level 122 Unity Warp) place you around the same area and will allow you to enter Ifrit's Cauldron as instructed below. Bring a total of three Ice Clusters to speed up the flame spouts along the way, if you don't, you'll have to wait up to 3 game hours (around 7 Earth minutes) for them to disappear. Bring Silent Oils and Prism Powders as bombs will aggro spell casting after removing invisible to trade a cluster.",
        "Consider taking a Garnet with you on this leg of the mission, as you can trade it to the headstone to receive the Opo-opo Necklace . You need to take the Fire Fragment before doing this.",
        "All three travel options ( Teleport-Yhoat , the Yhoator Jungle Survival Guide, or the Level 122 Unity Warp) place you around the same area and will allow you to enter Ifrit's Cauldron as instructed below. Bring a total of three Ice Clusters to speed up the flame spouts along the way, if you don't, you'll have to wait up to 3 game hours (around 7 Earth minutes) for them to disappear. Bring Silent Oils and Prism Powders as bombs will aggro spell casting after removing invisible to trade a cluster.",
        "Bring a total of three Ice Clusters to speed up the flame spouts along the way, if you don't, you'll have to wait up to 3 game hours (around 7 Earth minutes) for them to disappear. Bring Silent Oils and Prism Powders as bombs will aggro spell casting after removing invisible to trade a cluster.",
        "Bring Silent Oils and Prism Powders as bombs will aggro spell casting after removing invisible to trade a cluster.",
        "You need to take the Fire Fragment before doing this.",
        "Enter Ifrit's Cauldron from (G-6) in Yhoator Jungle . Alternatively take the Survival Guide warp if you've unlocked it to get to this entrance. When you enter, you'll be on Map 4. Head for (H-8) and through the middle exit, and you'll end up on Map 7. From Map 7, hug the left wall and head out the exit at (D-12) to continue to Map 5. On Map 5, head for (J-8), the only other exit, to get to Map 2. There is a Flame Spout around (H-6)/(H-7). Either wait it out, or trade an Ice Cluster . Waiting it out is safer, but can take extra time. On Map 2, run to (E-7) while hugging the left wall, and you'll be back on Map 7. Do not accidentally take the drop that is to the north of the tunnel at (G-8). On Map 7, hug the left wall on your way to (G-7) to enter Map 8. Do not accidentally take the drop slightly to the right. On Map 8, follow the tunnel to (C-7). This is the exit to Yuhtunga Jungle . There are two Flame Spouts on the way.",
        "Near the exit to Yuhtunga Jungle , you may run across the Ash Dragon . Your party is likely not able to take it if you are level 75, so be careful. During daytime hours (06:00 to 18:00), it's only aggressive to sound. During night time, however, it is True Sound. Take care when passing it, as it will mostly likely spell a wipe for your party.",
        "Once outside, gather everyone up and head for the tunnel under the waterfall at (K-7). The headstone is located around (L-6)/(L-7). Check the Cermet Headstone to spawn two Opo-opo NMs , Carthi and Tipha . They will both aggro through sneak and cannot be slept , but are susceptible to gravity and bind. Defeat both Opos and check the Cermet Headstone again to receive the Fire fragment . If you get a message saying \"Don't you have something better to do right now?\", keep checking the headstone until you get the KI.",
        "Alternatively take the Survival Guide warp if you've unlocked it to get to this entrance.",
        "When you enter, you'll be on Map 4. Head for (H-8) and through the middle exit, and you'll end up on Map 7.",
        "From Map 7, hug the left wall and head out the exit at (D-12) to continue to Map 5.",
        "On Map 5, head for (J-8), the only other exit, to get to Map 2. There is a Flame Spout around (H-6)/(H-7). Either wait it out, or trade an Ice Cluster . Waiting it out is safer, but can take extra time.",
        "On Map 2, run to (E-7) while hugging the left wall, and you'll be back on Map 7. Do not accidentally take the drop that is to the north of the tunnel at (G-8).",
        "On Map 7, hug the left wall on your way to (G-7) to enter Map 8. Do not accidentally take the drop slightly to the right.",
        "On Map 8, follow the tunnel to (C-7). This is the exit to Yuhtunga Jungle . There are two Flame Spouts on the way.",
        "During daytime hours (06:00 to 18:00), it's only aggressive to sound. During night time, however, it is True Sound. Take care when passing it, as it will mostly likely spell a wipe for your party.",
        "Take care when passing it, as it will mostly likely spell a wipe for your party.",
        "They will both aggro through sneak and cannot be slept , but are susceptible to gravity and bind.",
        "Defeat both Opos and check the Cermet Headstone again to receive the Fire fragment . If you get a message saying \"Don't you have something better to do right now?\", keep checking the headstone until you get the KI.",
        "If you get a message saying \"Don't you have something better to do right now?\", keep checking the headstone until you get the KI.",
        "Lightning Fragment:",
        "Travel to Behemoth's Dominion (G-9). Unity Warp Level 135 will be the fastest way to get here.",
        "Clear the area of mobs and check the headstone to spawn two Weapon NMs: Legendary Weapon (BLM/RDM) and Ancient Weapon (WAR) . Defeat them both and check the Cermet Headstone again to receive the Lightning fragment .",
        "It is possible to fight only one of the NMs , by using the Sneak -pull method. Sneak one member, pull one of the NMs and wait for the other to de-pop. Defeat the original and proceed. Both are susceptible to Bind and Gravity , but not sleep or silence. Both will use their 1-hour abilities around 50%. Legendary Weapon will use Manafont and begin casting back-to-back. Casts Diaga 2, Paralyze, Silence, Slow, Gravity, Cure IV, Protect/Shell, etc. Either can be defeated solo at level 75 with DoT and occasional nukes while kiting it around the King Behemoth spawn area. Ancient Weapon is not aspirable , but the Legendary Weapon is.",
        "Unity Warp Level 135 will be the fastest way to get here.",
        "Defeat them both and check the Cermet Headstone again to receive the Lightning fragment .",
        "Both are susceptible to Bind and Gravity , but not sleep or silence.",
        "Both will use their 1-hour abilities around 50%. Legendary Weapon will use Manafont and begin casting back-to-back. Casts Diaga 2, Paralyze, Silence, Slow, Gravity, Cure IV, Protect/Shell, etc. Either can be defeated solo at level 75 with DoT and occasional nukes while kiting it around the King Behemoth spawn area. Ancient Weapon is not aspirable , but the Legendary Weapon is.",
        "Legendary Weapon will use Manafont and begin casting back-to-back. Casts Diaga 2, Paralyze, Silence, Slow, Gravity, Cure IV, Protect/Shell, etc.",
        "Either can be defeated solo at level 75 with DoT and occasional nukes while kiting it around the King Behemoth spawn area. Ancient Weapon is not aspirable , but the Legendary Weapon is.",
        "Casts Diaga 2, Paralyze, Silence, Slow, Gravity, Cure IV, Protect/Shell, etc.",
        "Ancient Weapon is not aspirable , but the Legendary Weapon is.",
        "Wind Fragment:",
        "Consider taking a Rain Lily with you on this part of the mission. Trading it to the headstone will earn you a Flagellant's Rope . You need to take the Wind Fragment before doing this.",
        "Start off for Cape Teriggan , both the Home Point and Unity Warp 128 let out close to the Cermet Headstone .",
        "Head for (F-7) and locate the unmarked hidden tunnel (it is in the same general area as the tunnel to get to the Cloister of Gales ). Go north until you come out into another open area, taking another hidden tunnel at (G-5). Follow it until (H-5), where the headstone is located.",
        "Check the headstone to pop a Shadow NM named Axesarion the Wanderer . Defeat it and check the Cermet Headstone again to receive the Wind fragment .",
        "You need to take the Wind Fragment before doing this.",
        "Go north until you come out into another open area, taking another hidden tunnel at (G-5). Follow it until (H-5), where the headstone is located.",
        "Follow it until (H-5), where the headstone is located.",
        "Defeat it and check the Cermet Headstone again to receive the Wind fragment .",
        "Light Fragment:",
        "Proceed to The Sanctuary of Zi'Tah . Your goal is to get to (J-9) first. The Survival Guide /Outpost warp will get you closest to (J-9).",
        "From (J-9), entrance is at the South Eastern (SE) corner of the box, hug left wall till you're near the North Eastern corner of (I-7). This is the same area where Keeper of Halidom can spawn.",
        "Check the headstone to spawn a Doomed NM named Doomed Pilgrims . This NM hits fairly fast and hard, but should pose little trouble to a well balanced party of 65+.",
        "Defeat the NM and check the Cermet Headstone again to receive the Light fragment .",
        "Note : Come back to this headstone after completing ZM7: The Chamber of Oracles to receive a Bat Earring .",
        "The Survival Guide /Outpost warp will get you closest to (J-9).",
        "This is the same area where Keeper of Halidom can spawn.",
        "This NM hits fairly fast and hard, but should pose little trouble to a well balanced party of 65+.",
        "Upon obtaining the final fragment, you will receive the message, \"You now have all 8 fragments of light!\" and the mission will be complete.",
      }
    },
    {
      id = "mission_zilart_6",
      name = "Zilart Mission 6",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 6,
      game_id = 0,
      repeatable = false,
      steps = {
        "Note : You'll need to step on pads that require a certain weight. You'll either need 1 Galka , 3 Tarutaru or any combination of 2 of Hume / Elvaan / Mithra .",
        "(Optional: Go to Eastern Altepa Desert , and complete the quest Open Sesame for the Loadstone key item, allowing you to pass through the doors alone). If you have it already unlocked, you can use the Quicksand Caves Home Point #1 to get quick access to Chamber of Oracles . The Proto-Waypoint : Quicksand Caves is also a quick way to get the the Chamber, just drop down and follow the path, keeping west.",
        "If other people in your party are progressing with you: ensure everyone is on the mission Through the Quicksand Caves . If not, they have not properly completed the previous mission, check key items to see which is missing.",
        "If you're low level and not using Trusts , you'll want a party of level 65+. You will be entering a BCNM fight against 3 Antica NMs, who all have a TP attack that will Silence (Jamming Wave), mages should all bring Echo Drops .",
        "If you have it already unlocked, you can use the Quicksand Caves Home Point #1 to get quick access to Chamber of Oracles . The Proto-Waypoint : Quicksand Caves is also a quick way to get the the Chamber, just drop down and follow the path, keeping west.",
        "The Proto-Waypoint : Quicksand Caves is also a quick way to get the the Chamber, just drop down and follow the path, keeping west.",
        "If not, they have not properly completed the previous mission, check key items to see which is missing.",
        "Everything here is aggressive to sound, so make sure everyone has Sneak . Using the Unity Warp 125 will locate you in Western Altepa Desert (I-7).",
        "Proceed to Western Altepa Desert and head for the tunnel at (C/D-11) south side. Following this tunnel will bring you to an unmarked area of the desert.",
        "Head down the ramp to (D-12) and enter Quicksand Caves .",
        "Go to (I-9) and step on the weight pad and go through the door.",
        "Go west to (H-7) and use another weight pad to pass through a door.",
        "In the next room, drop down the hole to a hidden area.",
        "Head to (D-4) to zone in to the Chamber of Oracles .",
        "Using the Unity Warp 125 will locate you in Western Altepa Desert (I-7).",
        "Following this tunnel will bring you to an unmarked area of the desert.",
        "Get ready and enter the BCNM. You'll be facing 3 Antica NMs A dual boxed 75 BLM, 75 WHM and 75 THF/NIN can easily beat this BCNM. THF only took damage from occasional RNG attacks, and Magnetic cloud. You can use Trusts in this fight.",
        "Upon clearing the BC, you'll zone in to another area of the Chamber of Oracles, which starts the next mission.",
        "A dual boxed 75 BLM, 75 WHM and 75 THF/NIN can easily beat this BCNM. THF only took damage from occasional RNG attacks, and Magnetic cloud.",
        "You can use Trusts in this fight.",
        "Centurio V-III : Uses Invincible",
        "Triarius V-VIII : Uses Manafont",
        "Princeps V-XI : Uses Eagle Eye Shot",
        "Uses Invincible",
        "Uses Manafont",
        "Uses Eagle Eye Shot",
        "Recommended fight order of Centurio V-III (PLD) → Triarius V-VIII (BLM) → Princeps V-XI (RNG) .",
        "Open with a Sleepga, and then Silence the Paladin and the Black Mage.",
        "Defeat the Paladin first, as he can rebuff the others, as well as wake them up.",
        "Keep the BLM silenced, to render its Manafont useless.",
        "Finally, defeat the RNG, but be careful of Eagle Eye Shot .",
      }
    },
    {
      id = "mission_zilart_7",
      name = "Zilart Mission 7",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 7,
      game_id = 0,
      repeatable = false,
      steps = {
        "You'll be in a room with a large device. Check each of the 8 parts of the device to insert the fragments obtained in a previous mission. You'll be given a cutscene, thus starting the next mission.",
      }
    },
    {
      id = "mission_zilart_8",
      name = "Zilart Mission 8",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 8,
      game_id = 0,
      repeatable = false,
      steps = {
        "(Optional) Aldo's Decision: At the Tenshodo HQ in Lower Jeuno , speak to Aldo for a cutscene.",
        "Zone into Lower Delkfutt's Tower from Qufim Island or via Survival Guide for a cutscene.",
        "Zone into Stellar Fulcrum for a cutscene. Home Point # 1 in Upper Delkfutt's Tower puts you right at this zone. You can then use the teleporter.",
        "Having a Delkfutt Key or Delkfutt key will greatly speed this mission up.",
        "If you have a key, proceed to (E-8) on the first floor and go through the cermet door to the basement. Then proceed to (J-8) for another cermet door. In the middle of the spiral staircase at (H-8) click the ??? to be teleported to the 10th floor.",
        "If you do not have the key then you will have to climb the tower regularly.",
        "Home Point # 1 in Upper Delkfutt's Tower puts you right at this zone. You can then use the teleporter.",
        "Then proceed to (J-8) for another cermet door.",
        "In the middle of the spiral staircase at (H-8) click the ??? to be teleported to the 10th floor.",
        "Once you reach Upper Delkfutt's Tower by any means, head for (F-8) on the first map and then through the door. This area is not shown on the map.",
        "Climb the stairs to the 11th floor. You'll need Sneak and Invisible to avoid aggro from Bats and Giants. There are also dolls and pots which aggro magic.",
        "Proceed to (J-6) and go to the 12th floor.",
        "Head for (F-10) and go through the teleporter to enter the Stellar Fulcrum .",
        "Walk forward and click the Qe'lov Gate to enter the battlefield.",
        "This area is not shown on the map.",
        "You will enter a BCNM fight against Kam'lanaut . Buffs wear when entering the BC. Trusts can be used.",
        "Clearing this BC ends the mission.",
        "Trusts can be used.",
        "Great Wheel: AoE damage (~200) and Hate reset.",
        "Light Blade: Single target heavy damage (~700-1200). Has a charging time, and can be stunned. It has high range, and can be blinked by Utsusemi .",
        "Has a charging time, and can be stunned.",
        "It has high range, and can be blinked by Utsusemi .",
        "Will cast Silencega, Dispelga and Slowga .",
        "Can use an Elemental Blade attack which gives him an en-spell of that element. It also causes him to be healed by magic of that same element. Major nukes can heal him for a lot of damage if the wrong spell is used, so be careful. It can be Dispelled.",
        "Immune to Sleep and Silence .",
        "Approximately 10,000 HP.",
        "It also causes him to be healed by magic of that same element. Major nukes can heal him for a lot of damage if the wrong spell is used, so be careful. It can be Dispelled.",
        "Major nukes can heal him for a lot of damage if the wrong spell is used, so be careful. It can be Dispelled.",
      }
    },
    {
      id = "mission_zilart_9",
      name = "Zilart Mission 9",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 9,
      game_id = 0,
      repeatable = false,
      steps = {
        "(Optional) Head to the Tenshodo and speak to Aldo .",
        "Go to Norg and speak with Gilgamesh , who speaks of ruins north of The Sanctuary of Zi'Tah , and may be what Eald'narche is talking about. Click on the \"Oaken Door\" at (K-8) in Norg for the option to \"Open the door\"; Accepting this option starts the cut-scene.",
        "You may be on other missions related to Chains of Promathia or Rhapsodies of Vanadiel . Make sure you choose to \"Open the door\" to progress this particular mission.",
        "After the Cut-scene with Lion and Gilgamesh you will be standing outside the Oaken Door again and the next mission will have started.",
        "Click on the \"Oaken Door\" at (K-8) in Norg for the option to \"Open the door\"; Accepting this option starts the cut-scene.",
        "Make sure you choose to \"Open the door\" to progress this particular mission.",
      }
    },
    {
      id = "mission_zilart_10",
      name = "Zilart Mission 10",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 10,
      game_id = 0,
      repeatable = false,
      steps = {
        "Go to Ro'Maeve . You will need Sneak and Invisible through this area, but everything in-zone detects magic, so use Silent Oils and Prism Powders or cast Sneak and Invisible at the zone. You can now also use a mount in this zone.",
        "If you have it, Survival Guide to Ro'Maeve is the fastest way, it puts you right at the zone to Hall of the Gods . Unity Warp (125) will put you at the entrance of Ro'Maeve .",
        "Head for (H-5) and zone in to Hall of the Gods .",
        "Run through the hallway and check the Cermet Grate two times. You will now be on the next mission.",
        "You can now also use a mount in this zone.",
        "Unity Warp (125) will put you at the entrance of Ro'Maeve .",
      }
    },
    {
      id = "mission_zilart_11",
      name = "Zilart Mission 11",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 11,
      game_id = 0,
      repeatable = false,
      steps = {
        "Unable to progress any further, head back to Norg , open the door, and speak to Gilgamesh . He will speak of a Mithra who was once trying to sell a crystal. You will now be on the next mission.",
        "He will speak of a Mithra who was once trying to sell a crystal. You will now be on the next mission.",
        "You will now be on the next mission.",
      }
    },
    {
      id = "mission_zilart_12",
      name = "Zilart Mission 12",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 12,
      game_id = 0,
      repeatable = false,
      steps = {
        "Go to Rabao Home Point #2 and speak to Maryoh Comyujah , who is in (G-7) in front of the windmill. Chose the top option 'Sounds fair'. If you spam enter then you won't choose this.",
        "She will ask you to go to the Quicksand Caves (again..).",
        "Head for the secret entrance in Western Altepa Desert (C/D-11), (Same hidden zone as ZM6: Through the Quicksand Caves .) This Mission happens in a similar location in the caves, but on the opposite side of the area where you went before. Check the coordinates below to be sure. You can use the Proto-Waypoint in Rabao at (G-8) to get to Quicksand Caves and enter into the right map (but not the right hole, you still need to go to the other side of the map).",
        "Inside (on Map 5), go to (K-8) and through the pressure door, this will lead you to Map 6. On Map 6, head for (G-8) for another pressure door.",
        "Chose the top option 'Sounds fair'. If you spam enter then you won't choose this.",
        "This Mission happens in a similar location in the caves, but on the opposite side of the area where you went before. Check the coordinates below to be sure.",
        "You can use the Proto-Waypoint in Rabao at (G-8) to get to Quicksand Caves and enter into the right map (but not the right hole, you still need to go to the other side of the map).",
        "On Map 6, head for (G-8) for another pressure door.",
        "Enter and fall down the hole. Near where you fall, there is a ??? . Buff up and select \"Yes\" to dig and spawn a Pot NM Ancient Vessel . You may need to move very close to the ??? to get it to actually spawn. Once you kill the NM, check the ??? again. You will receive the Scrap of papyrus .",
        "Return to Rabao and speak to Maryoh Comyujah again. She will give you the Cerulean crystal .",
        "Head back to the Hall of the Gods, touch the sealed gate, and watch the cutscene.",
        "Go down the hallway and examine the Shimmering Circle for the last cutscene.",
        "Once you kill the NM, check the ??? again. You will receive the Scrap of papyrus .",
      }
    },
    {
      id = "mission_zilart_13",
      name = "Zilart Mission 13",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 13,
      game_id = 0,
      repeatable = false,
      steps = {
        "After the last cutscene where you teleport up, you will be granted access to Tu'Lia , otherwise known as \"sky\". You'll be able to use the shimmering circle you found downstairs to return anytime for future reference.",
        "Run forward to zone into Ru'Aun Gardens and begin the next mission. Don't forget to grab the Survival Guide just up ahead after you zone into Ru'Aun Gardens . If you have the quest for Prishe's Boots +1 active, a different cutscene will play the first time you enter the zone. Exit the zone and re-enter to receive the correct cutscene.",
        "Don't forget to grab the Survival Guide just up ahead after you zone into Ru'Aun Gardens .",
        "If you have the quest for Prishe's Boots +1 active, a different cutscene will play the first time you enter the zone. Exit the zone and re-enter to receive the correct cutscene.",
      }
    },
    {
      id = "mission_zilart_14",
      name = "Zilart Mission 14",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 14,
      game_id = 0,
      repeatable = false,
      steps = {
        "Note: The quest Divine Might allows you to confront all 5 bosses below simultaneously and complete this mission immediately, rather than fighting each boss separately. However, part of the quest requires you to receive an Ark Pentasphere during the full moon so check your Current Time in-game before going this route.",
        "Zone into Ru'Aun Gardens for a brief cutscene with Zeid and Aldo. If you have the quest for Prishe's Boots +1 active, a different cutscene will play the first time you enter the zone. Zone out and back in to trigger the proper cutscene.",
        "Proceed straight forward into the teleporter and enter The Shrine of Ru'Avitau from the (H-8) entrance in Ru'Aun Gardens . Survival Guide puts you close if you have it.",
        "Head north a short distance and examine the blank target at (G/H-11) for a cutscene.",
        "After the cutscene, return to Ru'Aun Gardens .",
        "There are 5 BC fights to complete this mission, each spread out across the entire zone. Take the red portals to get to the appropriate towers that you see around the outside edge of the zone. Ru'Aun Gardens is mostly safe from all aggro, except for the dolls which stand on blue pads, set in walls. Stay on the other side of the path from these and you'll be entirely safe. Everything detects magic except for birds. To give a brief description of how the portals work: The red portals lead to the islands in which you can access the La'Loff Amphitheater which leads to each of the fights (where the Home Points are set when you view the map). The red portals are already activated by default. After each fight you will warp back to the island you were originally on by taking a red portal from the Home Point island. What you have to do to get to the next fight is find the pincerstone (it looks like a pincer pointing to the sky with a blue stone between) on the side of the island in the direction you want to travel (Which will be counter-clockwise in this case, i.e. starting from West to East) These are marked by blue stars on the map for Ru'Aun Gardens on this page >>. On the first island the pincerstone is closer to the centre, but on subsequent islands it will be a small walk to your right once you warp back from the Home Point island. Activating the pincerstone will turn on the blue warp point which is located on the same side as the red portal but just to the left of it. (Imagine north is always pointing outside the circle, the blue warp point is south of the red one on the lower level). This will transport you to the next larger island and you can then take the red portal (Which is located on the other side to where you arrived) to the next Home Point island. Rinse and repeat all the way around. Basically all the larger and smaller islands are the same (with some minor differences but all points of interest are placed the same) except for the starting island in the south of the map. Note: there are two of each portal circle (blue and red) on either side of each island. The smaller circle is the warp point, and the larger one is where you land. The warp point has pincers around it.",
        "Visit each of the towers and zone inside, the BC area is called La'Loff Amphitheater . You will be facing 5 Ark Angels, who you first saw in the Throne Room, as each of the 5 races wearing black armor and have very pale, ghostly faces. Divine Might combines all 5 Ark Angels in a single fight, fought as an alliance. The mission itself, however, is individual fights, in 6 person BCs. At each tower, you'll have some time to prepare, and then enter to face off against the Ark Angel. Each tower is specific, so you'll need to visit them all. Each Ark Angel has 2 jobs, and can use the full abilities of each, as well as their respective weapons weaponskills.",
        "If you have the quest for Prishe's Boots +1 active, a different cutscene will play the first time you enter the zone. Zone out and back in to trigger the proper cutscene.",
        "Survival Guide puts you close if you have it.",
        "Ru'Aun Gardens is mostly safe from all aggro, except for the dolls which stand on blue pads, set in walls. Stay on the other side of the path from these and you'll be entirely safe. Everything detects magic except for birds.",
        "To give a brief description of how the portals work: The red portals lead to the islands in which you can access the La'Loff Amphitheater which leads to each of the fights (where the Home Points are set when you view the map). The red portals are already activated by default. After each fight you will warp back to the island you were originally on by taking a red portal from the Home Point island. What you have to do to get to the next fight is find the pincerstone (it looks like a pincer pointing to the sky with a blue stone between) on the side of the island in the direction you want to travel (Which will be counter-clockwise in this case, i.e. starting from West to East) These are marked by blue stars on the map for Ru'Aun Gardens on this page >>. On the first island the pincerstone is closer to the centre, but on subsequent islands it will be a small walk to your right once you warp back from the Home Point island. Activating the pincerstone will turn on the blue warp point which is located on the same side as the red portal but just to the left of it. (Imagine north is always pointing outside the circle, the blue warp point is south of the red one on the lower level). This will transport you to the next larger island and you can then take the red portal (Which is located on the other side to where you arrived) to the next Home Point island. Rinse and repeat all the way around. Basically all the larger and smaller islands are the same (with some minor differences but all points of interest are placed the same) except for the starting island in the south of the map. Note: there are two of each portal circle (blue and red) on either side of each island. The smaller circle is the warp point, and the larger one is where you land. The warp point has pincers around it.",
        "The red portals lead to the islands in which you can access the La'Loff Amphitheater which leads to each of the fights (where the Home Points are set when you view the map).",
        "The red portals are already activated by default.",
        "After each fight you will warp back to the island you were originally on by taking a red portal from the Home Point island. What you have to do to get to the next fight is find the pincerstone (it looks like a pincer pointing to the sky with a blue stone between) on the side of the island in the direction you want to travel (Which will be counter-clockwise in this case, i.e. starting from West to East) These are marked by blue stars on the map for Ru'Aun Gardens on this page >>.",
        "On the first island the pincerstone is closer to the centre, but on subsequent islands it will be a small walk to your right once you warp back from the Home Point island.",
        "Activating the pincerstone will turn on the blue warp point which is located on the same side as the red portal but just to the left of it. (Imagine north is always pointing outside the circle, the blue warp point is south of the red one on the lower level).",
        "This will transport you to the next larger island and you can then take the red portal (Which is located on the other side to where you arrived) to the next Home Point island.",
        "Rinse and repeat all the way around.",
        "Basically all the larger and smaller islands are the same (with some minor differences but all points of interest are placed the same) except for the starting island in the south of the map. Note: there are two of each portal circle (blue and red) on either side of each island. The smaller circle is the warp point, and the larger one is where you land. The warp point has pincers around it.",
        "These are marked by blue stars on the map for Ru'Aun Gardens on this page >>.",
        "Note: there are two of each portal circle (blue and red) on either side of each island. The smaller circle is the warp point, and the larger one is where you land. The warp point has pincers around it.",
        "You will be facing 5 Ark Angels, who you first saw in the Throne Room, as each of the 5 races wearing black armor and have very pale, ghostly faces. Divine Might combines all 5 Ark Angels in a single fight, fought as an alliance. The mission itself, however, is individual fights, in 6 person BCs.",
        "At each tower, you'll have some time to prepare, and then enter to face off against the Ark Angel. Each tower is specific, so you'll need to visit them all. Each Ark Angel has 2 jobs, and can use the full abilities of each, as well as their respective weapons weaponskills.",
        "Can use Mighty Strikes and Mijin Gakure .",
        "Uses the unique WS Cross Reaver which does cone damage (~500-900) and has an additional effect of Stun .",
        "The biggest single fear in this fight is Mijin Gakure , which can easily spell a wipe if used at high HP. Magic Mitigation such as Rampart , Shell , Fealty , and any other damage mitigation spells/Blood Pacts will help keep you alive; but it is non-elemental damage, so Bar spells have no effect. Beyond that, simply survive and defeat him.",
        "Uses the unique WS Amon Drive which does AoE damage (~100-300) and has an additional effect of Paralysis and Petrification . Absorbed by Utsusemi .",
        "Can use Manafont and Blood Weapon .",
        "Will teleport around the arena.",
        "Just fight him normally, try to stay out of range of the AoE.",
        "Can use Perfect Dodge and Charm .",
        "Uses the unique WS Havoc Spiral which does AoE damage (~100-300) and has an additional effect of Sleep . Absorbed by Utsusemi .",
        "Can Charm your tank regardless of whether or not her pet is still alive, so plan accordingly.",
        "Will summon a pet, usually a tiger, but can be a Mandragora as well. Sleep the pet and ignore it.",
        "Can use Invincible and Benediction .",
        "Uses the unique WS Dominion Slash which does AoE damage (~100-300) and has an additional effect of Silence . Absorbed by Utsusemi . Recommended to bring Echo Drops . It can also dispel buffs.",
        "Uses the unique ability Shield Strike which is a cone attack that does ~100 damage and Stun .",
        "Take care to avoid Spirits Within , as it can easily destroy your tank. Gravity and Bind and kite the NM is typically the best strategy.",
        "Surprisingly strong to fight around era level (75-80ish) when soloing with Trusts due to the AOE damage and status effects going out as Trust WHM's burn a lot of MP erasing and na-ing the whole party",
        "If soloing with Trusts on a brand new account -- your first Job to 99 -- you may wish to wait until you are 85+ or request help from someone to blow past this specific NM",
        "Wiped 2x as a 78 WAR/SAM with Perle set from Abyssea on, and with trusts Valaineral, Ayame, Semih Lafihna, and Yoran-Oran (UC)",
        "Can use Call Wyvern and Meikyo Shisui multiple times.",
        "Uses the unique WS Dragonfall which does AoE damage (~100-300) and has an additional effect of Bind . Absorbed by Utsusemi .",
        "Straight fight, NIN tank suggested to reduce WS damage from Meikyo Shisui.",
      }
    },
    {
      id = "mission_zilart_15",
      name = "Zilart Mission 15",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 15,
      game_id = 0,
      repeatable = false,
      steps = {
        "If you completed the previous mission by way of Divine Might and have yet to choose your reward, enter the Shrine of Ru'Avitau through the (H-9) entrance in Ru'Aun Gardens . This should force your log to change. Otherwise, simply select your earring from the location where you started Divine Might and choose your reward.",
        "Head for Norg and speak to Gilgamesh .",
        "Head back to Ru'Aun Gardens and go to any entrance to the Shrine of Ru'Avitau . Enter for a cutscene. Teleporting to the home point will also trigger the cutscene. You may find entering the shrine from (I-6) (near Ru'Aun Gardens Home Point #1) to save time approaching the next quest.",
        "You may find entering the shrine from (I-6) (near Ru'Aun Gardens Home Point #1) to save time approaching the next quest.",
      }
    },
    {
      id = "mission_zilart_16",
      name = "Zilart Mission 16",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 16,
      game_id = 0,
      repeatable = false,
      steps = {
        "The The Shrine of Ru'Avitau is full of magic aggro, so even mages should bring along Silent Oil and Prism Powder . Note that Ninjutsu and Spectral Jig are also options for applying Sneak (Status) and Invisible (Status) without potentially aggroing nearby enemies.",
        "Note that Ninjutsu and Spectral Jig are also options for applying Sneak (Status) and Invisible (Status) without potentially aggroing nearby enemies.",
        "You may need someone to operate the Yellow door. The closest Monolith to your location is around I/J-9/10.",
        "Go to (I-6) in Ru'Aun Gardens and enter the Shrine. You'll be on Map 1. Sneak and head south. Go past (J-7) through the first yellow door. Go west from here, to the room with 2 Monoliths in (H-7). You'll need Invisible, then go south around the square hallway filled with Aura Statue to another room with 2 Dark Elementals around (H-10).",
        "Go north, down a flight of stairs to the Celestial Nexus at (H-9).",
        "Gather together and get ready for the last BC of the expansion. You'll be fighting Eald'narche , who has two forms.",
        "Upon clearing the BC, you'll receive a final cutscene and be returned to the Hall of the Gods .",
        "Celestial Nexus",
        "Eald'narche - First Form",
        "Exoplate : Gaea Stream: Single target damage (~200). Absorbed by Utsusemi . Uranos Cascade: AoE physical damage (~200-400). Absorbed by Utsusemi . Cronos Sling: Cone attack physical damage (~300-600). Absorbed by Utsusemi . Phase Shift: AoE (large area) physical damage (~600-1300), Additional effect of Stun and/or Bind . Absorbed by Utsusemi . Used at around 66%, 33% and 1-2% HP. It gets progressively more powerful. At 1% the Exoplates will not die until they Phase Shift . It is possible to go below 66 and 33% before Phase Shift",
        "Eald'narche : Eald'narche uses ancient magic and will cast Sleepga II . Low HP (~2,000) will end him fairly quickly, however.",
        "Gaea Stream: Single target damage (~200). Absorbed by Utsusemi .",
        "Uranos Cascade: AoE physical damage (~200-400). Absorbed by Utsusemi .",
        "Cronos Sling: Cone attack physical damage (~300-600). Absorbed by Utsusemi .",
        "Phase Shift: AoE (large area) physical damage (~600-1300), Additional effect of Stun and/or Bind . Absorbed by Utsusemi . Used at around 66%, 33% and 1-2% HP. It gets progressively more powerful. At 1% the Exoplates will not die until they Phase Shift . It is possible to go below 66 and 33% before Phase Shift",
        "Used at around 66%, 33% and 1-2% HP. It gets progressively more powerful.",
        "At 1% the Exoplates will not die until they Phase Shift . It is possible to go below 66 and 33% before Phase Shift",
        "Eald'narche uses ancient magic and will cast Sleepga II . Low HP (~2,000) will end him fairly quickly, however.",
        "There will be 2 Orbitals , which have very little HP. They will be resummoned if killed. They heavily resist Lullaby , but Sleep is reliable.",
        "Exoplates surround Eald'narche and have about 10,000 HP. It does not melee.",
        "Go all out, and defeat the Exoplates as quick as possible. You'll want to keep mages far out of range for Phase Shift. When it appears time for a Phase Shift, try to get everyone healed to full and get shadows back up. This will negate most, if not all, damage.",
        "If you wipe, wait until you are ejected, as you'll aggro anywhere on the battlefield.",
        "Celestial Nexus",
        "Eald'narche - Second Form",
        "Vortex: Medium-range AoE, low damage (~100), with an additional effect of Terror and Bind . Absorbed by Utsusemi .",
        "Stellar Burst: AoE, low damage (~100), with an additional effect of Silence . Absorbed by Utsusemi .",
        "Omega Javelin: Single target damage (~150), with an additional effect of Petrification . Absorbed by Utsusemi .",
        "The second form is against Eald'narche only. He will teleport around like Ark Angel TT and cast various Black Magic spells, including Bindga .",
        "He still has relatively low HP (~2,500), but may or may not have a large defense and magic defense boost.",
        "You have 1 minute before he aggro's, regardless of your range from him.",
        "It has been observed that he may be heavily resistant to magic, however, a Tarutaru BLM/NIN was seen doing all of the damage to this form, ending the fight in 3 spells.",
        "He has very fast melee speed, but not quite the speed of Hundred Fists.",
        "Poison Potions and Stun can make the second form a lot easier.",
      }
    },
    {
      id = "mission_zilart_17",
      name = "Zilart Mission 17",
      type = "mission",
      location = "zilart",
      nation = "zilart",
      mission_index = 17,
      game_id = 0,
      repeatable = false,
      steps = {
        "Enter Norg for a cutscene with Gilgamesh . If you do not get a cutscene, proceed to the Captain's Chamber and speak to Gilgamesh there.",
        "Click on the Neptune's Spire Inn door in Lower Jeuno for another cutscene with Aldo . These can be done in any order, but both must be completed before zoning to Ru'Lude Gardens to trigger Shadows of the Departed . The Quest will not trigger unless sufficient progress has been made in other questlines, visit the page Shadows of the Departed for more details.",
        "These can be done in any order, but both must be completed before zoning to Ru'Lude Gardens to trigger Shadows of the Departed . The Quest will not trigger unless sufficient progress has been made in other questlines, visit the page Shadows of the Departed for more details.",
        "The Quest will not trigger unless sufficient progress has been made in other questlines, visit the page Shadows of the Departed for more details.",
      }
    },
}

return missions
